### ISSUE TITLE
Error: buildkit process has exited

### ISSUE THREAD

**Issue by jamesalucas** [earthly/earthly#1220]
We are seeing the buildkit process crash frequently in our CI server - we have 2 CentOS 8 boxes (20 CPUs with 40GB RAM) each of which host 10 Github runners and for any given build all 20 will be running different Earthly targets, although there is likely to be some common targets invoked by these.

When buildkit crashes the majority of the time all we see in the CI logs are one of the following errors:

`Error: error reading from server: EOF`
`Error: build target: build main: bkClient.Build: listing workers for Build: failed to list workers: Unavailable: connection closed.`

Presumably because buildkit terminated unexpectedly and severed the connection.

The docker logs on the server show the following:

```
panic: failed to get edge

goroutine 101 [running]:
github.com/moby/buildkit/solver.(*pipeFactory).NewInputRequest(0xc004a7df18, 0x0, 0x180f458, 0xc00041e5c0, 0xc00bdbf040, 0xc0075eb568, 0xc00245cff0)
        /src/solver/scheduler.go:354 +0x24b
github.com/moby/buildkit/solver.(*edge).createInputRequests(0xc0075eb040, 0x2, 0xc004a7df18, 0x0, 0x20c6128)
        /src/solver/edge.go:809 +0x328
github.com/moby/buildkit/solver.(*edge).unpark(0xc0075eb040, 0xc001801660, 0x1, 0x1, 0xc004a7de48, 0x0, 0x0, 0x20c6128, 0x0, 0x0, ...)
        /src/solver/edge.go:360 +0x17a
github.com/moby/buildkit/solver.(*scheduler).dispatch(0xc00055d7a0, 0xc0075eb040)
        /src/solver/scheduler.go:136 +0x425
github.com/moby/buildkit/solver.(*scheduler).loop(0xc00055d7a0)
        /src/solver/scheduler.go:104 +0x168
created by github.com/moby/buildkit/solver.newScheduler
        /src/solver/scheduler.go:35 +0x1b3
Error: buildkit process has exited
```

Not sure if this is the same issue or a different one, but I have also seen this in one of our logs:

```
Error: build target: build main: bkClient.Build: failed to solve: failed to prepare bdoo7cro9nsq17s69vnq9svax: failed to rename: rename /tmp/earthly/buildkit/runc-overlayfs/snapshots/snapshots/new-488976287 /tmp/earthly/buildkit/runc-overlayfs/snapshots/snapshots/97685: file exists
```

I have tried replicating this outside of CI but I'm so far unable to, so is there something I can do to help gather the information required to resolve this?

Thanks,

**Comment by jamesalucas** [comment]
I've just seen the same thing reported in moby/buildkit... https://github.com/moby/buildkit/issues/2303.

I have enabled BUILDKIT_DEBUG and BUILDKIT_SCHEDULER_DEBUG and have a large log file - would that be of any use?

**Comment by vladaionescu** [comment]
> I have enabled BUILDKIT_DEBUG and BUILDKIT_SCHEDULER_DEBUG and have a large log file - would that be of any use?

Maybe.. can't hurt to attach that in case anyone from buildkit finds a use for it.

**Comment by vladaionescu** [comment]
It's possible that a buildkit update would also make this go away magically. We should try that first.

**Comment by jamesalucas** [comment]
I've build `buildkitd` locally and have been experimenting with different log messages in our CI environment. So far I have established that the error happens because...

`NewInputRequest` makes a call to `getEdge(Edge)` and within `getEdge` it checks to see if the digest for the edge is active in the following bit of code:

```
func (jl *Solver) getEdge(e Edge) *edge {
	jl.mu.RLock()
	defer jl.mu.RUnlock()

	st, ok := jl.actives[e.Vertex.Digest()]
	if !ok {
		return nil
	}
	return st.getEdge(e.Index)
}
```

In the error scenario it is failing to find an entry in `jl.actives` for the edge's digest, returns `nil` which then causes the panic in `NewInputRequest`.

I have removed the panic and whilst the jobs fail when this (race condition?) happens, the `buildkitd` process doesn't die and therefore it's only a small fraction of jobs that error rather than all of the jobs that were in progress at the time. This is a vast improvement for us, but it would be great to determine why there isn't an entry in `jl.actives` that is expected.

Therefore I am currently looking to see if entries in `jl.actives` are being removed prematurely by logging each one that is deleted (in `deleteIfUnreferenced`), but even if I were to see that happening, I wouldn't have a clue how to resolve it! 

If anyone has any suggestions of things to try then I'd love to hear them. I will cross post this against the buildkit bug in case anyone there has any ideas too.

Thanks,

James

**Comment by jamesalucas** [comment]
I _think_ I have managed to confirm that the entries in `jl.actives` are being removed prematurely as I can see the following from my logging:

```
grep 2c4ac4dfeeeb84e66ab8348046fda65f600b93195ee19b87de914268c08a1058 711f69ac3cde_2.log
time="2021-09-29T12:39:20Z" level=info msg="> Deleting digest sha256:2c4ac4dfeeeb84e66ab8348046fda65f600b93195ee19b87de914268c08a1058 "
time="2021-09-29T12:40:08Z" level=info msg=">>> getEdge(Edge) edge sha256:2c4ac4dfeeeb84e66ab8348046fda65f600b93195ee19b87de914268c08a1058 [./packages/nest+yarn-files 17a2fd41-6ca8-42b3-8d05-166d45042252] COPY package.json ./packages/nest/ %!s(solver.Index=0). No active vertex. There are 548 active vertexes"
time="2021-09-29T12:40:10Z" level=info msg="> failed to get edge sha256:2c4ac4dfeeeb84e66ab8348046fda65f600b93195ee19b87de914268c08a1058 [./packages/nest+yarn-files 17a2fd41-6ca8-42b3-8d05-166d45042252] COPY package.json ./packages/nest/ currentState={%!s(solver.edgeStatusType=2) %!s(*solver.SharedCachedResult=<nil>) %!s(*solver.CacheMap=&{sha256:5da32dcaee25519f6a4ec51b2fa169515837349a513709edd66186fddcee87c3 [{ <nil> 0xe41e00} {sha256:545332ac15012117358e30c0f45950b6426a9be87463f2e0c82e615033e511b8 0xe49260 0xe41e00}] map[]}) [{%!s(*solver.CacheKey=&{{{0 0} 0 0 0 0} n6m72p99voqixllzyt5n6kujo [[{ {0xc001b7e480 0xc011e24870}}] [{sha256:545332ac15012117358e30c0f45950b6426a9be87463f2e0c82e615033e511b8 {0xc001b7e880 0xc00d30c8d0}} { {0xc00d1b6980 0xc007fbae60}}]] sha256:5da32dcaee25519f6a4ec51b2fa169515837349a513709edd66186fddcee87c3 0 map[0xc0032a3270:n6m72p99voqixllzyt5n6kujo] [ukfwfafw90v4t3wvocx6j5abc]}) %!s(*solver.exporter=&{0xc00d1b6b00 [0xc0260305f0] <nil> [] <nil> <nil>})}]} desiredState=complete"
```

So the digest that eventually fails is deleted just before it is used.

At this point I'm not sure how to proceed, I can see 2 possibilities:

1) Try and delay the deletion until the work that needs it has finished
2) Try and catch the error and assume the work has been completed and proceed on that assumption

(2) looks kind of hacky but I'm not sure where to start with (1)!

**Comment by vladaionescu** [comment]
Not sure either - perhaps you can ask on the #buildkit channel in the [Docker community slack](http://dockr.ly/slack). There are some really helpful people over there.

**Comment by vladaionescu** [comment]
Probably relevant:
* https://github.com/moby/buildkit/pull/2382
* https://github.com/moby/buildkit/pull/2385

**Comment by jamesalucas** [comment]
Thanks, I've been involved with testing the above MRs which replace the panic with an error so that buildkit doesn't exit, and I'm working on a fix for the underlying issue, so hopefully this will get fixed upstream soonish.
