### ISSUE TITLE
Display nice message when docker is not running

### ISSUE THREAD

**Issue by vladaionescu** [earthly/earthly#1242]
Arsene reports on Slack:

> Hello I have observed that the latest version does not display clean error message when docker is not running:

```
auto frontend could not be initialized, using stub: failed to autodetect a supported frontend
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x28 pc=0x1058277b8]

goroutine 1 [running]:
github.com/earthly/earthly/buildkitd.IsStarted(0x105c3d328, 0x14000310700, 0x10585b16c, 0x11, 0x105c4ddd8, 0x106394eb8, 0x140006bd208, 0x10, 0x140)
	github.com/earthly/earthly/buildkitd/buildkitd.go:460 +0xd8
github.com/earthly/earthly/buildkitd.MaybeStart(0x105c3d328, 0x14000310700, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x106394c40, ...)
	github.com/earthly/earthly/buildkitd/buildkitd.go:145 +0x58
github.com/earthly/earthly/buildkitd.NewClient(0x105c3d328, 0x14000310700, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x106394c40, ...)
	github.com/earthly/earthly/buildkitd/buildkitd.go:83 +0x160
main.(*earthlyApp).actionBuildImp(0x14000600480, 0x140006e4e40, 0x14000782ad0, 0x0, 0x1, 0x14000782ae0, 0x1, 0x1, 0x0, 0x0)
	command-line-arguments/main.go:2648 +0x218
main.(*earthlyApp).actionBuild(0x14000600480, 0x140006e4e40, 0x106350c40, 0x14000358000)
	command-line-arguments/main.go:2581 +0x250
github.com/urfave/cli/v2.(*App).RunContext(0x140000a8000, 0x105c3d328, 0x14000310700, 0x1400003c040, 0x2, 0x2, 0x0, 0x0)
	github.com/urfave/cli/v2@v2.3.0/app.go:322 +0x51c
main.(*earthlyApp).run(0x14000600480, 0x105c3d328, 0x14000310700, 0x1400003c040, 0x2, 0x2, 0x0)
	command-line-arguments/main.go:1469 +0x7c
main.main()
	command-line-arguments/main.go:248 +0x3a4
```

**Comment by mikejholly** [comment]
@vladaionescu, is this still happening for you? I noticed that when I stop the daemon and run a `docker` command, the daemon will be automatically started. In my case, the `earthly` command was completed successfully.
