### ISSUE TITLE
Panic when BUILDKIT_HOST=tcp://127.0.0.1:8372 and stub frontend is used

### ISSUE THREAD

**Issue by andrewsykim** [earthly/earthly#1340]
Inside of a container, if I use `BUILDKIT_HOST=tcp://127.0.0.1:8372` and I don't have docker installed, earthly uses the "stub" frontend. However, this leads to a nil panic:
```
Using tcp://127.0.0.1:8372 as buildkit daemon
loading config values from "/etc/.earthly/config.yml"
auto frontend could not be initialized, using stub: failed to autodetect a supported frontend
           bootstrap | Bootstrapping successful.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xf5a6a6]

goroutine 1 [running]:
github.com/earthly/earthly/buildkitd.IsStarted(0x1374048, 0xc00003cf00, 0x12127f0, 0x11, 0x1384768, 0x1aefc70, 0x4163fb, 0xc0000f2988, 0xc0006bd2d0)
	/earthly/buildkitd/buildkitd.go:460 +0x106
github.com/earthly/earthly/buildkitd.MaybeStart(0x1374048, 0xc00003cf00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1aef9f8, ...)
	/earthly/buildkitd/buildkitd.go:145 +0x85
github.com/earthly/earthly/buildkitd.NewClient(0x1374048, 0xc00003cf00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1aef9f8, ...)
	/earthly/buildkitd/buildkitd.go:83 +0x248
main.(*earthlyApp).actionBuildImp(0xc000503200, 0xc000321100, 0xc000119640, 0x0, 0x1, 0xc000119650, 0x1, 0x1, 0x0, 0x0)
	/earthly/cmd/earthly/main.go:2648 +0x32f
main.(*earthlyApp).actionBuild(0xc000503200, 0xc000321100, 0x1a4b280, 0xc000366000)
	/earthly/cmd/earthly/main.go:2581 +0x339
github.com/urfave/cli/v2.(*App).RunContext(0xc0004d2000, 0x1374048, 0xc00003cf00, 0xc000136000, 0x4, 0x4, 0x0, 0x0)
	/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:322 +0x6fe
main.(*earthlyApp).run(0xc000503200, 0x1374048, 0xc00003cf00, 0xc000136000, 0x4, 0x4, 0x0)
	/earthly/cmd/earthly/main.go:1469 +0xad
main.main()
	/earthly/cmd/earthly/main.go:248 +0x485
``` 

It seems like the problem is that there is a special "remote buildkit" check [here](https://github.com/earthly/earthly/blob/main/buildkitd/buildkitd.go#L65-L77) that directly returns the buildkit client instead of trying to start docker. However, when using a local address this check is skipped and the stub frontend returns a nil value that eventually results in a panic.

**Comment by jazzdan** [comment]
This also happens if Docker is installed, but the Docker daemon is not running.
