### ISSUE TITLE
bootstrap "panic: runtime error"

### ISSUE THREAD

**Issue by btc** [earthly/earthly#1393]
fresh install of earthly results in a panic on my macOS 12 system.

```
λ. brew install earthly/earthly/earthly; earthly bootstrap                                                                                                             2
Warning: earthly/earthly/earthly 0.5.24 is already installed and up-to-date.
To reinstall 0.5.24, run:
  brew reinstall earthly
auto frontend could not be initialized, using stub: failed to autodetect a supported frontend
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x4b5d106]

goroutine 1 [running]:
github.com/earthly/earthly/buildkitd.IsStarted(0x4f6a828, 0xc0003aaf00, 0x4e0829b, 0x11, 0x4f7b108, 0x56e10f8, 0x0, 0x0, 0x0)
        github.com/earthly/earthly/buildkitd/buildkitd.go:460 +0x106
github.com/earthly/earthly/buildkitd.MaybeStart(0x4f6a828, 0xc0003aaf00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x56e0e90, ...)
        github.com/earthly/earthly/buildkitd/buildkitd.go:145 +0x85
github.com/earthly/earthly/buildkitd.NewClient(0x4f6a828, 0xc0003aaf00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x56e0e90, ...)
        github.com/earthly/earthly/buildkitd/buildkitd.go:83 +0x248
main.(*earthlyApp).bootstrap(0xc000081200, 0xc0003ab280, 0x0, 0x0)
        command-line-arguments/main.go:1706 +0x56f
main.(*earthlyApp).actionBootstrap(0xc000081200, 0xc0003ab280, 0xc0000b0f00, 0xc0000b0f90)
        command-line-arguments/main.go:1652 +0x3d7
github.com/urfave/cli/v2.(*Command).Run(0xc0001c6000, 0xc000635100, 0x0, 0x0)
        github.com/urfave/cli/v2@v2.3.0/command.go:163 +0x4dd
github.com/urfave/cli/v2.(*App).RunContext(0xc00060a4e0, 0x4f6a828, 0xc0003aaf00, 0xc0001ba000, 0x2, 0x2, 0x0, 0x0)
        github.com/urfave/cli/v2@v2.3.0/app.go:313 +0x810
main.(*earthlyApp).run(0xc000081200, 0x4f6a828, 0xc0003aaf00, 0xc0001ba000, 0x2, 0x2, 0x0)
        command-line-arguments/main.go:1469 +0xad
main.main()
        command-line-arguments/main.go:248 +0x485
```

```
www  (btc/0017) λ. earthly -v
earthly version v0.5.24 darwin/amd64; macOS
```

**Comment by andrewsykim** [comment]
Seems like this could be related to https://github.com/earthly/earthly/issues/1340. 

Do you have docker or podman installed on your machine?

**Comment by btc** [comment]
Docker.app is installed. 

However, Docker.app was not running upon invocation of `bootstrap`.

Now, it is running and bootstrap succeeded. 

I can see the need for it to be running. I see that it is listed in the prerequisites and that I glossed over it.

**Comment by andrewsykim** [comment]
Fwiw the error message we currently have is a bit cryptic, @alexcb actually merged a patch recently (https://github.com/earthly/earthly/pull/1382) that should make it more obvious in the future that docker wasn't running

**Comment by btc** [comment]
thanks. 🙏🏽
