### ISSUE TITLE
WSL2 install not working

### ISSUE THREAD

**Issue by elsucht** [earthly/earthly#1398]
Following the installation procedure for Windows under WSL2 (Ubuntu 20.04 )gives me the error shown below.
What am I missing?
`auto frontend could not be initialized, using stub: failed to autodetect a supported frontend
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xf5a6a6]

goroutine 1 [running]:
github.com/earthly/earthly/buildkitd.IsStarted(0x1374048, 0xc000292540, 0x12127f0, 0x11, 0x1384768, 0x1aefc70, 0x0, 0x0, 0x0)
        /earthly/buildkitd/buildkitd.go:460 +0x106
github.com/earthly/earthly/buildkitd.MaybeStart(0x1374048, 0xc000292540, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1aef9f8, ...)
        /earthly/buildkitd/buildkitd.go:145 +0x85
github.com/earthly/earthly/buildkitd.NewClient(0x1374048, 0xc000292540, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1aef9f8, ...)
        /earthly/buildkitd/buildkitd.go:83 +0x248
main.(*earthlyApp).bootstrap(0xc000710480, 0xc000149040, 0x0, 0x0)
        /earthly/cmd/earthly/main.go:1706 +0x56f
main.(*earthlyApp).actionBootstrap(0xc000710480, 0xc000149040, 0xc000142300, 0xc000142330)
        /earthly/cmd/earthly/main.go:1652 +0x3d7
github.com/urfave/cli/v2.(*Command).Run(0xc000138480, 0xc000148e40, 0x0, 0x0)
        /go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:163 +0x4dd
github.com/urfave/cli/v2.(*App).RunContext(0xc0000a8000, 0x1374048, 0xc000292540, 0xc00003c040, 0x2, 0x2, 0x0, 0x0)
        /go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:313 +0x810
main.(*earthlyApp).run(0xc000710480, 0x1374048, 0xc000292540, 0xc00003c040, 0x2, 0x2, 0x0)
        /earthly/cmd/earthly/main.go:1469 +0xad
main.main()
        /earthly/cmd/earthly/main.go:248 +0x485`

**Comment by dchw** [comment]
Is `docker` available on your WSL2 distros `$PATH`? You could check this by running `which docker`. If does not exist, try [enabling the advanced integration with your preferred WSL distribution](https://docs.docker.com/desktop/windows/wsl/).

This only happens when `earthly` cannot find a `docker` or `podman` binary to use.

**Comment by skluthe** [comment]
I think I may be running into the same issue. I'm trying to use FROM DOCKERFILE in my earthfile though which I guess could cause it:
```bash
     node:16-alpine | --> Load metadata linux/amd64
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xd90ba7]

goroutine 84 [running]:
github.com/moby/buildkit/frontend/dockerfile/dockerfile2llb.Dockerfile2LLB({_, _}, {_, _, _}, {{0x0, 0x0}, {0x120e800, 0xc00073c810}, 0xc000a59320, ...})
        /go/pkg/mod/github.com/earthly/buildkit@v0.0.1-0.20220118235757-8d4eb6b24e72/frontend/dockerfile/dockerfile2llb/convert.go:107 +0x3ac7
github.com/earthly/earthly/earthfile2llb.(*Converter).FromDockerfile(0xc0004fcf00, {0x122e388, 0xc0003370c0}, {0xc000b95750, 0xf}, {0x0, 0x0}, {0x0, 0x0}, 0x0, ...)
        /earthly/earthfile2llb/converter.go:314 +0x13c5
github.com/earthly/earthly/earthfile2llb.(*Interpreter).handleFromDockerfile(0xc000a8ac60, {0x122e388, 0xc0003370c0}, {{0x10be3f2, 0xf}, {0xc0008377e0, 0x1, 0x1}, 0x0, 0xc000a92510})
        /earthly/earthfile2llb/interpreter.go:610 +0x6e7
github.com/earthly/earthly/earthfile2llb.(*Interpreter).handleCommand(0xc000a8ac60, {0x122e388, 0xc0003370c0}, {{0x10be3f2, 0xf}, {0xc0008377e0, 0x1, 0x1}, 0x0, 0xc000a92510})
        /earthly/earthfile2llb/interpreter.go:200 +0x15d4        
github.com/earthly/earthly/earthfile2llb.(*Interpreter).handleStatement(0xc000a8ac60, {0x122e388, 0xc0003370c0}, {0xc0009cb700, 0x0, 0x0, 0x0, 0xc000a924e0})
        /earthly/earthfile2llb/interpreter.go:152 +0x33c
github.com/earthly/earthly/earthfile2llb.(*Interpreter).handleBlock(0xc000a8ac60, {0x122e388, 0xc0003370c0}, {0xc000a8e8c0, 0x122e388, 0x4})
        /earthly/earthfile2llb/interpreter.go:100 +0x145
github.com/earthly/earthly/earthfile2llb.(*Interpreter).handleTarget(0xc000a8ac60, {0x122e388, 0xc0003370c0}, {{0xc00014bb78, 0x11}, {0xc000a8e8c0, 0x3, 0x4}, 0xc000a923c0})
        /earthly/earthfile2llb/interpreter.go:88 +0x1f6
github.com/earthly/earthly/earthfile2llb.(*Interpreter).Run(0xc000a8ac60, {0x122e388, 0xc0003370c0}, {0x0, {0xc000a8d0e0, 0x2, 0x2}, {0xc000a81e00, 0x2, 0x2}, ...})
        /earthly/earthfile2llb/interpreter.go:76 +0x2d2
github.com/earthly/earthly/earthfile2llb.Earthfile2LLB({_, _}, {{0x0, 0x0}, {0x0, 0x0}, {0x10b151d, 0x1}, {0x0, 0x0}, ...}, ...)  
        /earthly/earthfile2llb/earthfile2llb.go:161 +0x774       
github.com/earthly/earthly/builder.(*Builder).convertAndBuild.func1({0x122e388, 0xc0009981c0}, {0x12379c8, 0xc00037e880})
        /earthly/builder/builder.go:184 +0x46d
github.com/moby/buildkit/frontend/gateway/grpcclient.(*grpcClient).Run(0xc00037e880, {0x122e388, 0xc0009981c0}, 0xc0009967e0)     
        /go/pkg/mod/github.com/earthly/buildkit@v0.0.1-0.20220118235757-8d4eb6b24e72/frontend/gateway/grpcclient/client.go:188 +0x1bb
github.com/moby/buildkit/client.(*Client).Build.func2({0xc0002ee301, 0x19}, 0xc00018c3f0)
        /go/pkg/mod/github.com/earthly/buildkit@v0.0.1-0.20220118235757-8d4eb6b24e72/client/build.go:56 +0x286
github.com/moby/buildkit/client.(*Client).solve.func3()
        /go/pkg/mod/github.com/earthly/buildkit@v0.0.1-0.20220118235757-8d4eb6b24e72/client/solve.go:242 +0x57
golang.org/x/sync/errgroup.(*Group).Go.func1()
        /go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x67
created by golang.org/x/sync/errgroup.(*Group).Go
        /go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x92
```

```bash
user@DESKTOP-F172J96:/mnt/c/Users/user/dev/Work/Apps$ which dock
er
/usr/bin/docker
user@DESKTOP-F172J96:/mnt/c/Users/user/dev/Work/Apps$ docker ps
CONTAINER ID   IMAGE                      COMMAND                
  CREATED          STATUS          PORTS                         
                       NAMES
79e2d5bca59a   earthly/buildkitd:v0.6.6   "/usr/bin/entrypoint…"   21 minutes ago   Up 21 minutes   127.0.0.1:8371->8371/tcp, 127.0.0.1:8373->8373/tcp   earthly-buildkitd
```

This is my earthfile:
```yaml
FROM node:16-alpine
WORKDIR /app


baseimage:
  FROM DOCKERFILE ./baseimage/
  SAVE IMAGE base:latest

service-deps:
  BUILD +baseimage
  FROM DOCKERFILE ./service/
  SAVE IMAGE service:latest

#some comments happen here
```
