### ISSUE TITLE
Questions/issues around sources of `known_hosts`

### ISSUE THREAD

**Issue by rrjjvv** [earthly/earthly#1769]
I'll start by phrasing these as questions since I'm not sure if they are bugs, intended functionality, or in-between.  These are all in the context of earthly itself and its git operations (directly, via `GIT CLONE`, and indirectly, when referencing remote targets).  Additionally, they are in the context of using private/self-hosted repos.

1. Is there a reason why the system's file (`/etc/ssh/ssh_known_hosts`) is not used as a source of keys?
2. Is the `serverkey` option for git supposed to be GA (and usable by normal end-users)?
3. Usage of `strict_host_key_checking` (setting to `false`) incurs a large (4.5 minute) delay (but see below why I'm not opening an issue for this yet)

### System (`/etc/ssh/ssh_known_hosts`) keys
This is not a blocking or major issue, but I lost quite a bit of time discovering this the hard way.

I never hit this before since virtually all my usage until now has been running "as me" (where my user `known_hosts` had entries from normal daily usage) or as a dedicated CI user (with a pre-created user `known_hosts`).  I hit this when using the earthly docker image in combination with remote targets.

Whenever I create an image that requires git access, I add our keys to the system file so it doesn't matter what user is being used at the time (i.e., can flip between `USER alice` and `USER root` without worrying about creating user-specific key files).  I copied that same pattern in an earthly-derived image, and found it didn't work.

Since that file is in a well-known, standardized location, is the exact same format as `.ssh/known_hosts`, and is generally world-readable (in my experience), I can't think of any obvious reason why it can't/shouldn't work.

### `serverkey` availibility

_Largely a lazy in-line copy/paste of https://github.com/earthly/earthly/issues/1758#issuecomment-1075920825_

I noticed that the config also allows for specifying keys for the host: https://github.com/earthly/earthly/blob/32146712e74d1762a9bf8b16b15e3f229df6dd48/config/config.go#L98

That is **not** covered in the public docs.  If that's intentional, read no further.  If it's intended to be used and the lack of documentation is oversight, then hopefully you can tell at a quick glance if this is misuse on my part (thus documentation) or if it's really a bug (and I'd be happy to create a proper issue if that's the case).

It appears that at startup, the keys provided via config are added to a global 'pool' of keys, outside the scope of a matcher: https://github.com/earthly/earthly/blob/32146712e74d1762a9bf8b16b15e3f229df6dd48/buildcontext/gitlookup.go#L161

However, when doing a clone (in this case, it's an indirect result of resolving a remote target), I get https://github.com/earthly/earthly/blob/32146712e74d1762a9bf8b16b15e3f229df6dd48/buildcontext/gitlookup.go#L553

Working backwards, only the user's `known_hosts` and the hard-coded well-known keys are referenced: https://github.com/earthly/earthly/blob/32146712e74d1762a9bf8b16b15e3f229df6dd48/buildcontext/gitlookup.go#L295-L301
It doesn't appear that the `keyScans` on `GitLookup` are ever referenced.  I can't immediately think of reasons of why they can't or shouldn't be honored.

### Build lag using  `strict_host_key_checking: false`

I discovered this during the course of working through the two issues above.  This was solely a diagnostic step and not something I'd do for real-world usage.  It feels like it might be related to #1760, and possibly even fixed by it (though I've done no actual investigation).  So I'm happy to effectively ignore this until #1760 is released; if the issue still remains, I can fill in more details if needed.

**Comment by alexcb** [comment]
> Is there a reason why the system's file (/etc/ssh/ssh_known_hosts) is not used as a source of keys?

I think this is an oversight, if it exists we should pull them in by default.

> Is the serverkey option for git supposed to be GA (and usable by normal end-users)?

It should be; however, you raise an excellent point on why it's not documented. And grepping for `serverkey` doesn't show any integration tests. I suspect this was overlooked and needs some attention.

> Usage of strict_host_key_checking (setting to false) incurs a large (4.5 minute) delay (but see below why I'm not opening an issue for this yet)

:fearful: This does seem odd indeed! I would be curious to know if the ssh-timeout fixed it or not. Perhaps you can try running it via the `./earthly` script (see https://github.com/earthly/earthly/blob/main/CONTRIBUTING.md#using-earthly-prerelease ). If you're keen you can create an symlink such as `ln -s /path/to/github/earthly/earthly/earthly ~/bin/earthly-latest` to make it easier to quickly try using the latest version.

**Comment by rrjjvv** [comment]
Cool, thanks for confirming the intent on the first two.  I'm sure they're probably both trivial for you, but by the same token, probably within my capabilities.  I'd be happy to take it on if you want.  (I have more grandiose ideas to lay on you down the road, so don't want to tire you out with this easy stuff of mine!)

For the delay issue, I hadn't thought about using the pre-release.  It should be relatively easy for me to replicate that way.  (I believe you also publish pre-release docker images as well; this behavior was on a CI system that I don't known so uses earthly images rather than binaries.)

**Comment by rrjjvv** [comment]
@alexcb Quick update:

On the first two items (and my offer to implement them), I quickly regretted it (Go is nowhere close to a "native" language for me... it took ten minutes to write (my way), then a couple hours trying to make it look idiomatic; I suspect it still isn't).  The tests should at least be useful though.  Just let me know if you're interested.

As far as the lag time with disabled host checking... unfortunately, the timeout fix didn't solve it.  (Dockerhub claims there is a "prerelease" tag, but nothing appears to actually exist.  I pulled "latest", and it contains `"EARTHLY_GIT_HASH=422f019ebc32855c7b642e7d750ca7fafb471427"` in the environment; that commit is from three days ago, so I assume is effectively the same as "prerelease".)

Later I'll see if I can spot anything by walking through the code, but here's what the behavior "looks like":
```
11:26:49  Status: Downloaded newer image for earthly/earthly:latest
11:26:49  DOCKER_HOST is not set
11:26:49  Using tcp://35199a78468e:8372 as buildkit daemon
11:26:49  loading config values from "/etc/.earthly/config.yml"
11:26:49  Local registry host is specified while using remote buildkit. Local registry will not be used.
11:26:49             bootstrap | Bootstrapping successful.
11:26:49  
11:26:49   1. Init 🚀
11:26:49  ————————————————————————————————————————————————————————————————————————————————
11:26:49  
11:26:50  
11:26:50  
11:26:50   2. Build 🔧
11:26:50  ————————————————————————————————————————————————————————————————————————————————
11:26:50  
11:26:50         internal-term | connecting to shellrepeater on 35199a78468e:8373
11:26:50   earthly/dind:alpine | --> Load metadata linux/amd64
11:26:50   earthly/dind:alpine | Completed in 697.483617ms
11:26:56               ongoing | 
11:27:01               ongoing | 

<repeats about 20 times on a regular basis>

11:28:56               ongoing | 
11:28:58  s//g/p/foo-mock.git# | Completed in 187.362879ms
11:28:58              internal | Completed in 626.902423ms
11:28:58  s//g/p/foo-mock.git# | Completed in 68.833µs
11:29:04               ongoing | 

<repeats about 20 more times>

11:31:03               ongoing | 
11:31:06               context | --> git context git.example.com/pipe/foo-mock+image
11:31:06               context | Completed in 49.339µs
11:31:06  s//g/p/foo-mock.git# | Completed in 63.363µs

<snip output of actual execution>

11:31:16                 +test | Completed in 8.828894355s
11:31:16                output | --> exporting outputs
11:31:16                output | Completed in 1.426936ms
11:31:16  Summary of timing information
11:31:16  Note that the times do not include the expansion of commands like BUILD, FROM, COPY (artifact).
11:31:16                 +test | () 8.836794101s
11:31:16              internal | () 2.177239622s
11:31:16   earthly/dind:alpine | () 697.483617ms
11:31:16  s//g/p/foo-mock.git# | () 187.495075ms
11:31:16                   1/5 | () 9.36169ms
11:31:16                output | () 1.426936ms
11:31:16                   5/5 | () 167.08µs
11:31:16               context | () 98.678µs
11:31:16  ===============================================================
11:31:16  Total       	11.910066799s
11:31:16  Total (real)	4m26.36294342s
```

The minimal Earthfile responsible:
```Earthfile
VERSION 0.6

test:
    FROM earthly/dind:alpine
    WITH DOCKER --load enviromatic=git.example.com/pipe/foo-mock+image
        RUN docker inspect foo
    END
```
(where we have a custom matcher, valid auth, no known hosts, but requesting strict checking be disabled)

**Comment by alexcb** [comment]
#1795 implements reading from `/etc/ssh/ssh_known_hosts`

**Comment by alexcb** [comment]
Unfortunately I can't replicate the timeout issue, are you able to replicate the problem on multiple machines?

Do you run into similar timeouts when you simply run `earthly git.example.com/pipe/foo-mock+image`?

Does it happen on a host that doesn't require a custom pattern/substitute, for example an `./earthly/config.yml` like this:
```
git:
    "github.com":
       auth: ssh
       user: git
       strict_host_key_checking: false
```

**Comment by rrjjvv** [comment]
> #1795 implements reading from `/etc/ssh/ssh_known_hosts`

Nice!  I'm not nearly as ashamed at my implementation; it closely matches yours.  There is one minor difference.  In practice it may not make a difference, but it looks like failure to read the user's file will stop the system's file from being read.  The more I think about it, the more I do think it's not worth worrying about.

I'll scrap my own local code, but the (integration) test I wrote should still be valid, if you want it.  Maybe that change was too trivial to warrant its own test, but you can have it (I can inline it here, slap it in a gist, or whatever).

> Unfortunately I can't replicate the timeout issue, are you able to replicate the problem on multiple machines?

I think so, but even if not, I'm guessing I could.  I fully suspect this is a networking issue; that every host in "their" CI setup would exhibit the same behavior.  I had not seen this on "my" CI system, but it's on different network segment with different controls/layers.

On a hunch, I did a quick experiment.  If some of my assertions are correct, then this solves it.  If not, I'm very confident that it'll make the real issue obvious.

I had no reason to think there was any kind of bug when I started, but I wondered "what if something assumes SSH is always on port 22":
```
$ time ssh git.example.com
ssh: connect to host git.example.com port 22: Connection timed out

real    2m10.333s
user    0m0.012s
sys     0m0.000s
```

Very consistent.  And my lag time from above would be in the neighborhood of `4m14` and `4m26` (`4m26.36294342s-11.910066799s), which was also very consistent.  As if there were two sequential SSH calls.  (I imagine one call is to get the metadata to see whether it's a cache hit, then a second call to actually do the clone, or something to that effect.)

Now, may I present: https://github.com/earthly/earthly/blob/e5d699740bc65fc97ff325c9c27d132210a02a6e/buildcontext/gitlookup.go#L413

That's clearly a bug.  I very, very badly want that to be the issue, as everything above cleanly fits and it's an easy fix.  And it might still be the reason (or contributor), but these assumptions would need to be explained:
1. It would mean that my assumption that your timeout fix was present in the `:latest` image was bad (more on that below)
2. It would mean that my matcher that declares `auth: ssh` is not being respected (as that bad SSH connection only happens when dealing with an `auto` matcher
3. How `strict_host_key_checking: false` is required to get this lag, and that setting isn't even used until after that bad SSH connection is established.

The only thing that comes to close to explaining the last two is if the processing isn't actually "linear" like I assume.  It's hard to explain what I mean, so I won't try.  Of course there's the most rationale explanation of all... I have no clue what I'm talking about, and my findings from earlier were just coincidences and/or red herrings.

On the timeout issue, I had noticed that the timeout setting was vague on what it really meant... connection timeout?  read timeout?  idle timeout?  etc.  I ripped out that piece of code to make a standalone program; I stripped it down to
```
	config := &ssh.ClientConfig{
		User: "git",
		Auth: []ssh.AuthMethod{
			ssh.PublicKeysCallback(agent.NewClient(sshAgent).Signers),
		},
		//Timeout: time.Second * 3,
	}
```
Running against our host on (invalid) 22, I get the the same `2m10` delay with no explicit timeout, and does truly stop after three seconds after setting it.  I'm fairly certain the timeout is working... I was either not using your changes or something else is actually responsible.

---

See if you can make anything from my observations and guesses.  If you don't have any epiphanies, I'll conduct additional experiments.  Based on these findings (and some I didn't bother mentioning), I'm now fairly confident this isn't specific to "their" network (but our general corporate network) nor anything specific to CI machinery/wiring.  In other words, assuming I can duplicate on a bare host under my full control, I can iterate through experiments much more quickly (and being more confident in the results).

**Comment by rrjjvv** [comment]
> https://github.com/earthly/earthly/blob/559046c09097a333428b07b4771c227a846128e5/tests/git-ssh-server/Earthfile would be the location to extend the tests

Yup, mine is a copy/paste/edit of one of those.  The mini-tests it did within it:
```
# Keyscans set at the system level, not user

# They can be present in both locations

# Even if the system's entry is incorrect, that's fine if the user's is legit

# If the user's is bad, while the system's is good, one would think it should fail.  But it would appear that ssh itself
# will cycle through everything it knows to find a match (thus should succeed).  So should we.
```

> Have you tried running with --verbose?

I had, but it didn't provide anything useful (to my eyes).  It indirectly increased my confidence that there was a blocking operation (network) in play; during the entire stream of "ongoing" messages, only one debugging message was output.  One of those "solver" messages.  I _might_ still have a build record with the exact message, but it seem insightful.

The notes/theories about HTTPS timeouts would be a little harder to verify, since our internal git server *does* listen on conventional 443, and egress to 443 on the internet is generally allowed (unlike 22).

While I _can_ do many of those experiments you suggested in the same way I did the previous ones, I'll have more confidence in the results if I can run them in a more controlled manner.  There's too much strangeness as it is and don't want to be responsible for sending us down rabbit holes (esp. since we're talking about an anti-feature 😄).

Once I can do this (maybe tonight), I can crank out all of these experiments in a controlled, reproducible, and automated manner.  (Reproducible in *my* environment at least.)

**Comment by rrjjvv** [comment]
Okay, I was able to replicate the behavior on a bare VM.  I think that is the only good news.  These results largely validate everything from above, which is a bad thing, because they make no sense.

Not all of the combinations make sense, but I wanted to be complete nonetheless.  And there are actually 24 executions... each of those 8 scenarios was done with three versions.  But for each scenario, each version was identical in terms of pass/fail and reason for failure, and the difference in execution times were not different enough to warrant breaking them out.  In other words, all three versions behaved identically.

Versions used:
```
earthly-old version v0.6.10 3929cf684c8ea8c0987502517160b0eab52b017f linux/amd64; CentOS 7
earthly-release version v0.6.13 66ae40bb5b03769635a8a0bd0d5976dfc244514c linux/amd64; CentOS 7
earthly-prerelease version prerelease-e5d699740bc65fc97ff325c9c27d132210a02a6e e5d699740bc65fc97ff325c9c27d132210a02a6e linux/amd64; CentOS 7
```

There was no particular reason for using `0.6.10` except it was already on the host from a previous test.  I doubted it would tell us anything useful (but it actually did), but there was no harm in trying.

Summary/Notes:
1. The generic 3 second timeout (which should be present in both `0.6.13` as well as the pre-release) is having no impact (given that the timings are virtually identical to the old release version)
2. The very first scenario, as far as execution time, mirrors that of a plain `ssh` to our server on port 22 (which is invalid)
3. The fifth scenario is basically my original report.  Though it succeeds, it takes almost exactly twice as long as the failure in the first scenario.

The behavior is identical to two back-to-back bogus SSH connections.

|  SSH agent (w/ key loaded) | `known_hosts` present | `strict_host_key_checking` enabled | Success | Time | Failure reason |
| --- | --- | --- | --- | --- | --- |
| N | N | N | N | 2m8s | `unknown service moby.sshforward.v1.SSH` |
| N | N | Y | N | .8s | `no known_hosts entries exist` |
| N | Y | N | N | .8s | `unknown service moby.sshforward.v1.SSH` |
| N | Y | Y | N | .8s | `unknown service moby.sshforward.v1.SSH` |
| Y | N | N | Y | 4m20s | |
| Y | N | Y | N | .8s | `no known_hosts entries exist` |
| Y | Y | N | Y | 6s | |
| Y | Y | Y | Y | 6s | |

I'm ommitting the raw logs, since there are lots of them and very repetitive/not interesting from what I can tell.  I can easily provide them if you want.  Or if it might be valuable, I can run the scripts with `--debug` and give you a raw dump.

The config used (with minimal redaction):
```
global:
    disable_analytics: true
    disable_log_sharing: true
    cache_size_pct: 85
    buildkit_additional_config: |
        [registry."docker.io"]
          mirrors = ["docker.example.com"]
git:
    git.example.com:
        pattern: 'git.example.com/([^/]+)/([^/]+)'
        substitute: 'ssh://git.example.com:7999/$1/$2.git'
        auth: ssh
        strict_host_key_checking: true
    github.com:
        auth: https
    git.kernel.org:
        auth: https
```

Script that generated those results (if you want to double-check my work):
```shell
#!/bin/sh

EARTHLY_NO_CACHE=true

AGENT="No"
if [ -n "${SSH_AUTH_SOCK}" ]; then
    ssh-add ~/.ssh/gitcode
    AGENT="Have"
fi

rm -f ~/.ssh/known_hosts
[ -f /etc/ssh/ssh_known_hosts ] && exit 1

echo "********* $AGENT agent, no hosts, no keys, no checking ************"
earthly config 'git."git.example.com".strict_host_key_checking' false
for i in old release prerelease; do
    echo ">>>>>>>>>>> $i"
    exe=earthly-${i}
    $exe -v
    $exe bootstrap
    time $exe -P +test
    echo -e "<<<<<<<<<<< $i\n\n"
done

echo "********* $AGENT agent, no hosts, no keys, with checking ************"
earthly config 'git."git.example.com".strict_host_key_checking' true
for i in old release prerelease; do
    echo ">>>>>>>>>>> $i"
    exe=earthly-${i}
    $exe -v
    $exe bootstrap
    time $exe -P +test
    echo -e "<<<<<<<<<<< $i\n\n"
done

ssh-keyscan -p 7999 git.example.com 2>/dev/null > ~/.ssh/known_hosts
echo "********* $AGENT agent, with hosts, no keys, no checking ************"
earthly config 'git."git.example.com".strict_host_key_checking' false
for i in old release prerelease; do
    echo ">>>>>>>>>>> $i"
    exe=earthly-${i}
    $exe -v
    $exe bootstrap
    time $exe -P +test
    echo -e "<<<<<<<<<<< $i\n\n"
done

echo "********* $AGENT agent, with hosts, no keys, with checking ************"
earthly config 'git."git.example.com".strict_host_key_checking' true
for i in old release prerelease; do
    echo ">>>>>>>>>>> $i"
    exe=earthly-${i}
    $exe -v
    $exe bootstrap
    time $exe -P +test
    echo -e "<<<<<<<<<<< $i\n\n"
done
```

That script was run twice:
```
$ ./no-agent-run.sh 2>&1 | tee no-agent.txt
$ ssh-agent ./no-agent-run.sh 2>&1 | tee with-agent.txt  # and key was loaded
```

Time permitting, tomorrow I'll run some of your previous proposed experiments, as well as run the original experiments through `strace` (to see if the similarity to bogus SSH connections is coincidental or is actually what's happening).

**Comment by alexcb** [comment]
I'm stuck on how to get the `git clone https://.......` to timeout correctly; see https://github.com/moby/buildkit/issues/2791#issuecomment-1093100440

**Comment by rrjjvv** [comment]
Okay, I struck gold.  The world makes sense again.  I only took it as far as to identify the culprit.  If it hadn't taken so long for me tot figure out how to run this in a debugger (and figure out what diagnostic tools were available), I may have attempted to provide a fix (as well as explicitly answer some of the early questions based on this new knowledge).

Culprit (yes, other codebase):
https://github.com/earthly/buildkit/blob/f126d5cedf8a91de9948f374b982cce3fb5649f6/client/llb/source.go#L263-L267

I got there compliments of the 'hidden' `EARTHLY_PROFILER` flag:
```
goroutine 93 [IO wait]:
internal/poll.runtime_pollWait(0x7efc94731c68, 0x77)
	/opt/go1.17.8.linux-amd64/src/runtime/netpoll.go:234 +0x89
internal/poll.(*pollDesc).wait(0xc000b63180, 0x10c5f29, 0x0)
	/opt/go1.17.8.linux-amd64/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitWrite(...)
	/opt/go1.17.8.linux-amd64/src/internal/poll/fd_poll_runtime.go:93
internal/poll.(*FD).WaitWrite(...)
	/opt/go1.17.8.linux-amd64/src/internal/poll/fd_unix.go:529
net.(*netFD).connect(0xc000b63180, {0x1247618, 0xc0001a8000}, {0xc0004baed8, 0x40ecb4}, {0x1229860, 0xc0001f8b20})
	/opt/go1.17.8.linux-amd64/src/net/fd_unix.go:142 +0x717
net.(*netFD).dial(0xc000b63180, {0x1247618, 0xc0001a8000}, {0x1251498, 0x0}, {0x1251498, 0xc0008224b0}, 0xc0004bb0c8)
	/opt/go1.17.8.linux-amd64/src/net/sock_posix.go:150 +0x379
net.socket({0x1247618, 0xc0001a8000}, {0x10c5f29, 0x3}, 0x2, 0x1, 0x0, 0xc8, {0x1251498, 0x0}, ...)
	/opt/go1.17.8.linux-amd64/src/net/sock_posix.go:71 +0x2a5
net.internetSocket({0x1247618, 0xc0001a8000}, {0x10c5f29, 0x3}, {0x1251498, 0x0}, {0x1251498, 0xc0008224b0}, 0xc000b7eee0, 0x0, ...)
	/opt/go1.17.8.linux-amd64/src/net/ipsock_posix.go:142 +0xf8
net.(*sysDialer).doDialTCP(0xc000b63100, {0x1247618, 0xc0001a8000}, 0x0, 0x11)
	/opt/go1.17.8.linux-amd64/src/net/tcpsock_posix.go:66 +0xa5
net.(*sysDialer).dialTCP(0x1, {0x1247618, 0xc0001a8000}, 0xc000465320, 0xc000465350)
	/opt/go1.17.8.linux-amd64/src/net/tcpsock_posix.go:62 +0x59
net.(*sysDialer).dialSingle(0xc000b63100, {0x1247618, 0xc0001a8000}, {0x1237838, 0xc0008224b0})
	/opt/go1.17.8.linux-amd64/src/net/dial.go:583 +0x28b
net.(*sysDialer).dialSerial(0xc000b63100, {0x1247618, 0xc0001a8000}, {0xc000b9af30, 0x1, 0x10c6599})
	/opt/go1.17.8.linux-amd64/src/net/dial.go:551 +0x312
net.(*Dialer).DialContext(0xc0004bb498, {0x1247618, 0xc0001a8000}, {0x10c5f29, 0x3}, {0xc0000d0ba0, 0xc0002f1346})
	/opt/go1.17.8.linux-amd64/src/net/dial.go:428 +0x736
net.(*Dialer).Dial(...)
	/opt/go1.17.8.linux-amd64/src/net/dial.go:351
net.DialTimeout({0x10c5f29, 0x40f007}, {0xc0000d0ba0, 0x16}, 0x1111d04)
	/opt/go1.17.8.linux-amd64/src/net/dial.go:334 +0x85
golang.org/x/crypto/ssh.Dial({0x10c5f29, 0x11}, {0xc0000d0ba0, 0x14}, 0xc0004bb580)
	/home/robertovillarreal/go/pkg/mod/golang.org/x/crypto@v0.0.0-20220131195533-30dcbda58838/ssh/client.go:186 +0x3b
github.com/moby/buildkit/util/sshutil.SSHKeyScan({0xc0002f1346, 0x11})
	/home/robertovillarreal/go/pkg/mod/github.com/earthly/buildkit@v0.0.1-0.20220330184959-f126d5cedf8a/util/sshutil/keyscan.go:42 +0xf1
github.com/moby/buildkit/client/llb.Git({0xc0002f1340, 0x36}, {0x0, 0x0}, {0xc0004bbbc8, 0x2, 0x0})
	/home/robertovillarreal/go/pkg/mod/github.com/earthly/buildkit@v0.0.1-0.20220330184959-f126d5cedf8a/client/llb/source.go:267 +0x658
github.com/earthly/earthly/buildcontext.(*gitResolver).resolveGitProject.func1({0x1247960, 0xc000bb0aa0}, {0xf19e60, 0xc000b9ae40})
	/home/robertovillarreal/workspace/external/earthly/buildcontext/git.go:185 +0x44a
github.com/earthly/earthly/util/syncutil/synccache.(*SyncCache).Do.func1()
	/home/robertovillarreal/workspace/external/earthly/util/syncutil/synccache/synccache.go:44 +0x50
created by github.com/earthly/earthly/util/syncutil/synccache.(*SyncCache).Do
	/home/robertovillarreal/workspace/external/earthly/util/syncutil/synccache/synccache.go:40 +0x165
```

And for convenience (to see what actual values are in play at that point):
![image](https://user-images.githubusercontent.com/4579303/162680867-db1c65e4-8b7a-448c-9bac-0a0bff218102.png)


So I believe the ideal fix is two-fold:
1. The actual `host:port` combination needs to be passed in (the comments on `SSHKeyScan()` as well as cursory look at the code suggest everything would work as expected if the port hadn't been dropped)
2. As a preventative measure (as well as consistency), add the same change you did in #1760 to https://github.com/earthly/buildkit/blob/earthly-main/util/sshutil/keyscan.go#L37-L39

**Comment by rrjjvv** [comment]
@alexcb Since I knew the root cause, I was able to write a test that exhibits the behavior in a controlled fashion and can serve as a skeleton for the test that verifies the fix (whether the fix is eliminating the unnecessary scan, doing a scan against the correct location, timeout, or any combination of those).

Somewhere in `tests/git-ssh-server/Earthfile`:
```Earthfile
test-with-custom-matcher2:
    FROM ./setup+server \
        --DOCKERHUB_AUTH=$DOCKERHUB_AUTH \
        --DOCKERHUB_USER_SECRET=$DOCKERHUB_USER_SECRET \
        --DOCKERHUB_TOKEN_SECRET=$DOCKERHUB_TOKEN_SECRET \
        --DOCKERHUB_MIRROR=$DOCKERHUB_MIRROR \
        --DOCKERHUB_MIRROR_INSECURE=$DOCKERHUB_MIRROR_INSECURE \
        --SSHD_RSA=true \
        --SSHD_ED25519=true \
        --USER_RSA=true \
        --USER_ED25519=false
    RUN echo "Port 2222" >> /etc/ssh/sshd_config
    RUN apk add --no-cache pv

    RUN --no-cache echo "#!/bin/sh
set -ex

# first ensure these two /etc/hosts entries are working
ping -c 1 git.example.com
ping -c 1 buildkitsandbox

# load in preauthorized key
eval \$(ssh-agent)
ssh-add /root/self-hosted-rsa-key
ssh-add -l

# Setup auth to be ssh; with custom pattern/sub that converts 'funnyserver/repo' to 'ssh://git@git.example.com:2222/home/git/testuser/repo.git'
earthly --config \$earthly_config config 'git.\"git.example.com\"' '{\"auth\": \"ssh\", \"user\": \"git\", \"pattern\": \"funnyserver/([^/]+)\", \"substitute\": \"ssh://git@git.example.com:2222/home/git/testuser/\$1.git\", \"strict_host_key_checking\": false}'
cat \$earthly_config

# With no checking, this should be fast and no attempts to scan for keys
nc -l -p 22 > /tmp/nc.out &
echo \$! > /tmp/nc.pid
/usr/bin/time -f '%e' -o /tmp/test.time.fast earthly --config \$earthly_config --verbose +test-from
kill \$(cat /tmp/nc.pid)
! grep -q '^SSH' /tmp/nc.out

# Clear out known_hosts
rm -f ~/.ssh/known_hosts

# With no checking *and* no keys, we'd expect the same behavior as above.  In reality, a keyscan is done (even though
# we have no interest in checking), and against the wrong port.

# 11 characters repeated 6 times at 1 byte/sec. is good for about 66 seconds of tarpitting
for i in \$(seq 1 6); do echo -ne \"I am slow\r\n\"; done | pv -q -L 1 | nc -l -p 22 > /tmp/nc.out &
echo \$! > /tmp/nc.pid
/usr/bin/time -f '%e' -o /tmp/test.time.slow earthly --config \$earthly_config --verbose +test-from
# Identification will be 'SSH-2.0-<UA>'
grep '^SSH-' /tmp/nc.out

# busybox 'time' doesn't allow for formatting to integral values and the shell can't process floats, so strip them manually
fast=\$(cat /tmp/test.time.fast | sed 's/\..*//')
slow=\$(cat /tmp/test.time.slow | sed 's/\..*//')
[ \"\$slow\" -gt 60 ] && [ \"\$fast\" -lt 60 ]

" >/tmp/test-earthly-script && chmod +x /tmp/test-earthly-script
    DO +RUN_EARTHLY_ARGS --pre_command=start-sshd --earthfile=from-funnyserver.earth --exec_cmd=/tmp/test-earthly-script
```

And added to `tests/git-ssh-server/from-funnyserver.earth`:
```Earthfile
test-from:
    FROM funnyserver/repo:main+base
```

(Credit goes to [endlessh](https://github.com/skeeto/endlessh)  for giving me the first workable test, but after seeing how/why it worked, it was easy to remove that dependency for the sake of a more easily copy/pastable/disposable test.)

Out of the three potential solutions (overarching timeout, scanning the correct location, and omitting the scan entirely), I could take a stab at the second one.  The third is probably harder (and riskier, in terms of unintended consequences) than it looks on the surface, and you're already attempting the first.

**Comment by alexcb** [comment]
#1905 relates to this issues and was released under v0.6.15

It should now be possible to configure a self-hosted bitbucket server with the new `port` config option:

```
git:
    "my-bitbucket-host.example.com":
       auth: ssh
       user: git
       port: 7999   # <--- new option
```

or without key checking:

```
git:
    "my-bitbucket-host.example.com":
       auth: ssh
       user: git
       port: 7999
       strict_host_key_checking: false
```
