### ISSUE TITLE
`RUN --push` and `SAVE ARTIFACT AS LOCAL` crashes (sometimes)

### ISSUE THREAD

**Issue by alexcb** [earthly/earthly#1849]
```Earthfile
VERSION 0.6
a:
    FROM alpine
    WORKDIR /data
    RUN echo "Main screen turn on" > opperator
    RUN --push echo boom > someone-sent-us-up-the-bomb
    SAVE ARTIFACT * AS LOCAL ur-base/
```

Running `earthly --push +a` will *sometimes* output both files locally:

```
# ls -l ur-base/
total 8
-rw-r--r-- 1 alex alex 20 Apr 19 08:50 opperator
-rw-r--r-- 1 alex alex  5 Apr 19 08:50 someone-sent-us-up-the-bomb
```

however other times, it will produce:

```
$ earthly --push +a 

 1. Init 🚀
————————————————————————————————————————————————————————————————————————————————

           buildkitd | Found buildkit daemon as docker container (earthly-buildkitd)


 2. Build 🔧
————————————————————————————————————————————————————————————————————————————————

              alpine | --> Load metadata linux/amd64
                  +a | --> FROM alpine
                  +a | [██████████] 100% resolve docker.io/library/alpine@sha256:4edbd2beb5f78b1014028f4fbb99f3237d9561100b6881aabbf5acce2c4f9454
                  +a | *cached* --> WORKDIR /data
                  +a | *cached* --> RUN echo "Main screen turn on" > opperator
              output | --> exporting outputs


 3. Push ⏫
————————————————————————————————————————————————————————————————————————————————

                  +a | --> RUN --push echo boom > someone-sent-us-up-the-bomb
                  +a | --> SAVE ARTIFACT * +a/* AS LOCAL ur-base/
Shareable link: https://ci.earthly.dev/logs?logId=ff3e7a31-50f0-4a2d-9409-4accb9bf4b4e
Error: error reading from server: EOF
```

with buildkitd crashing:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0xc25889]

goroutine 16659 [running]:
github.com/moby/buildkit/solver.(*Job).walkBuildInfo(0xc00157bb00, {0x1663b00, 0xc001a2c140}, {0x47, {0x166c5b8, 0xc002181a80}}, 0xc000c13170)
	/src/solver/jobs.go:524 +0x169
github.com/moby/buildkit/solver.(*Job).walkBuildInfo(0xc00157bb00, {0x1663b00, 0xc001a2c140}, {0x0, {0x166c5b8, 0xc002181ac0}}, 0xc000c13170)
	/src/solver/jobs.go:532 +0x1dc
github.com/moby/buildkit/solver.(*Job).Build(0xc00157bb00, {0x1663b00, 0xc001a2c140}, {0x0, {0x166c638, 0xc00157a000}})
	/src/solver/jobs.go:517 +0x3af
github.com/moby/buildkit/solver/llbsolver.(*llbBridge).loadResult(0xc001a547d0, {0x1663b00, 0xc001a2c140}, 0x28, {0x0, 0x0, 0x46940e})
	/src/solver/llbsolver/bridge.go:139 +0x3e3
github.com/moby/buildkit/solver/llbsolver.newResultProxy.func1({0x1663b00, 0xc001a2c140})
	/src/solver/llbsolver/bridge.go:190 +0x65
github.com/moby/buildkit/solver/llbsolver.(*resultProxy).Result.func2({0x1663b00, 0xc001a2c140})
	/src/solver/llbsolver/bridge.go:271 +0x150
github.com/moby/buildkit/util/flightcontrol.(*call).run(0xc001aac090)
	/src/util/flightcontrol/flightcontrol.go:121 +0x5e
sync.(*Once).doSlow(0x440d65, 0xc0018777d0)
	/usr/local/go/src/sync/once.go:68 +0xd2
sync.(*Once).Do(0x1636040, 0xc000a499b0)
	/usr/local/go/src/sync/once.go:59 +0x1f
created by github.com/moby/buildkit/util/flightcontrol.(*call).wait
	/src/util/flightcontrol/flightcontrol.go:164 +0x44f
time="2022-04-19T15:51:06Z" level=error msg="reading from connection failed: EOF" app=shellrepeater
Error: buildkit process has exited
```

**Comment by jazzdan** [comment]
We're experiencing this when running `+playwright-update-snapshots` in [this Earthfile](https://github.com/replayio/devtools/blob/eb7b278ab776d28c3462bd1cad387c6b8e8be553/packages/bvaughn-architecture-demo/playwright/Earthfile)

**Comment by bvaughn** [comment]
Just chiming in to add a bit more context to @jazzdan's note above: This is a pretty major blocker for us on the Replay side at the moment, as it completely blocks our process of syncing Playwright (visual) snapshot updates which in turn blocks our ability to land UI changes to the new console we're working on.
