### ISSUE TITLE
One-off `earthly` crash on startup

### ISSUE THREAD

**Issue by nschmeller** [earthly/earthly#1864]
Hey! I got a strange crash with Earthly while I was using it for another task. I couldn't reproduce it. Nothing crazy was going on in my system at the time. Output of my `uname -a`: `Linux ip-172-31-24-188 5.13.0-1019-aws #21~20.04.1-Ubuntu SMP Wed Mar 16 11:54:08 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

Earthly run logs + stack trace:

```
❯ aws-vault exec default -- sh -c 'earthly +test-fim-verify-execution --AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID --AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY --AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN'

 1. Init 🚀
————————————————————————————————————————————————————————————————————————————————

           buildkitd | Found buildkit daemon as docker container (earthly-buildkitd)


 2. Build 🔧
————————————————————————————————————————————————————————————————————————————————

 earthly/dind:ubuntu | --> Load metadata linux/amd64
             context | --> local context ../../..
             context | --> local context ../../..
               +base | --> FROM earthly/dind:ubuntu
         context | --> local context ../../..
             context | --> local context ../../..
             context | --> local context ../../..
             context | --> local context ../../..
             context | --> local context ../../..
             context | --> local context ../../..
             context | --> local context ../../..
               +base | [          ]   0% resolve docker.io/earthly/dind:ubuntu@sha256:44862b35e0bc7771ac55cf292526cdc8b041dec920aa25d81b9a804bf5d590c5
             context | --> local context ../../..
             context | --> local context ../../..
               +base | [██████████] 100% resolve docker.io/earthly/dind:ubuntu@sha256:44862b35e0bc7771ac55cf292526cdc8b041dec920aa25d81b9a804bf5d590c5
             ongoing | context (4 seconds ago), context (4 seconds ago) and 9 others
     context | [          ]   0% transferring ../../..:
             context | transferred 2 file(s) for context ../../.. (144 kB, 2 file/dir stat[██████████] 100% transferring ../../..:
             context | [          ]   0% transferring ../../..:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xb50ef2]

goroutine 500 [running]:
github.com/tonistiigi/fsutil.Walk.func1({0xc000f5a1e0, 0x1e}, {0x0, 0x0}, {0x123a2c0, 0xc000f4a7b0})
        /go/pkg/mod/github.com/earthly/fsutil@v0.0.0-20220118225905-42fa88fbe869/walker.go:138 +0xff2
path/filepath.walk({0xc000f44900, 0x8}, {0x1262610, 0xc000f54f70}, 0xc001337d40)
        /usr/local/go/src/path/filepath/path.go:438 +0x20d
path/filepath.Walk({0xc000f44900, 0x8}, 0xc0006d9d40)
        /usr/local/go/src/path/filepath/path.go:505 +0x6c
github.com/tonistiigi/fsutil.Walk({0x1258680, 0xc000f48a00}, {0xc000b8eea0, 0x8}, 0xc000f40c60, 0xc000b4e660)
        /go/pkg/mod/github.com/earthly/fsutil@v0.0.0-20220118225905-42fa88fbe869/walker.go:110 +0x954
github.com/tonistiigi/fsutil.(*fs).Walk(0xc000cf6c60, {0x1258680, 0xc000f48a00}, 0xc000936ca8)
        /go/pkg/mod/github.com/earthly/fsutil@v0.0.0-20220118225905-42fa88fbe869/fs.go:36 +0x3d
github.com/tonistiigi/fsutil.(*sender).walk(0xc000f40d20, {0x1258680, 0xc000f48a00})
        /go/pkg/mod/github.com/earthly/fsutil@v0.0.0-20220118225905-42fa88fbe869/send.go:155 +0xa6
github.com/tonistiigi/fsutil.(*sender).run.func1()
        /go/pkg/mod/github.com/earthly/fsutil@v0.0.0-20220118225905-42fa88fbe869/send.go:62 +0x2e
golang.org/x/sync/errgroup.(*Group).Go.func1()
        /go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x67
created by golang.org/x/sync/errgroup.(*Group).Go
```

Hope this is useful!

**Comment by brandonSc** [comment]
Thanks for the report @nschmeller 

Seems the panic would have originated [around here](https://github.com/earthly/fsutil/blob/42fa88fbe869cc8429d029545f197b4df4f5bc17/walker.go#L138) (`os.FileInfo` was nil?). Not super familiar with the `fsutil` code, Maybe @alexcb has a better idea of what went wrong here?
