### ISSUE TITLE
panic in Windows

### ISSUE THREAD

**Issue by cupen** [earthly/earthly#1898]
My env:
* Windows 10

install from https://github.com/earthly/earthly/releases/download/v0.6.14/earthly-windows-amd64.exe

```bash
\> earthly
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/wille/osutil.GetVersion()
        /go/pkg/mod/github.com/wille/osutil@v0.0.0-20201124133013-e7a03eb09286/os_windows.go:45 +0x1fc
github.com/wille/osutil.GetDisplay(...)
        /go/pkg/mod/github.com/wille/osutil@v0.0.0-20201124133013-e7a03eb09286/os_windows.go:73
main.getPlatform()
        /earthly/cmd/earthly/main.go:318 +0x1d
main.getVersionPlatform()
        /earthly/cmd/earthly/main.go:314 +0x125
main.newEarthlyApp({0xc000001801, 0xc00079fd00}, {{0x0, 0x0}, 0x0, 0x0, {0x0, 0x0}, 0x0, 0x0, ...})
        /earthly/cmd/earthly/main.go:360 +0x335
main.main()
        /earthly/cmd/earthly/main.go:235 +0x373
```

**Comment by cupen** [comment]
I install from source, but no changes. It seems like that it's a bug in osutil.

**Comment by cupen** [comment]
En... This problem will triggered in windows with Chinese language pack.
https://github.com/wille/osutil/issues/3
