### ISSUE TITLE
`SAVE ARTIFACT` discrepancies when using `--if-exists`

### ISSUE THREAD

**Issue by rrjjvv** [earthly/earthly#2014]
Summary: this is the first time I've utilized `SAVE ARTIFACT --if-exists`, which I thought would solve one of my (unrelated) problems, but made things worse.  My usage of that construct resulted in every build failing, _even when the files existed_.  In other words, simply removing `--if-exists` actually turned my failing build into a passing build.  Based on the below scenarios, I'm pretty sure I've isolated the issue to the location of the source file being saved.

1. I'm pretty sure the issue is within the `SAVE ARTIFACT` code itself, but it doesn't actually trigger the behavior
2. The `COPY` command (parenthesized or 'plain' artifact form doesn't appear to matter) actually results in the error (`BUILD`ing the target works just fine)
3. It appears to be specific to directories (and likely files) that are specified with absolute paths

I've only verified this with `0.6.15`; it didn't seem like something that would have been recently introduced.  The workaround appears to simply specifying a relative path in tandem with `WORKDIR`, or using an earthly `IF` block to look for existence and using plain `SAVE ARTIFACT` inside that block.

---

There are a large number of variations in my example, but they were my attempt at isolating the actual issue and figuring out a workaround.  There are a few other factors I wanted to try (esp. files vs. directories, wildcards vs. not, and `AS LOCAL` variants), but this was extremely tedious as it was.  All of these scenarios involve directories that *actually* exist (which was my situation, and makes this issue 'worse').  I'm fairly certain the presence/existence isn't a factor itself, and has everything to do with the switch itself (the 'empty wildcard'), probably combined with path calculation/normalization/sanitization.

The actual output is not interesting, so omitting most of it.  The  `+work-fine` target are the variations that work fine.  Every member of the `+broken` fails.  The first one is actually a panic; first few lines of the trace:
```
panic: runtime error: slice bounds out of range [1:0]

goroutine 84 [running]:
github.com/earthly/earthly/util/llbutil.CopyOp({{{0x126cab0, 0xc000b8e300}, 0xc000b06910, {0x0, 0x0}, 0x0, {0x0, 0x0, 0x0}, 0x0}}, ...)
	/earthly/util/llbutil/copyop.go:42 +0xb32
github.com/earthly/earthly/earthfile2llb.(*Converter).SaveArtifact(0xc000d20000, {0x127e180, 0xc000a80200}, {0xc0009a853a, 0x2}, {0xc0009a8546, 0x1}, {0x0, 0x0}, 0x0, ...)
	/earthly/earthfile2llb/converter.go:741 +0x885
github.com/earthly/earthly/earthfile2llb.(*Interpreter).handleSaveArtifact(0xc000b00ea0, {0x127e180, 0xc000a80200}, {{0x1103dc1, 0xd}, {0xc0008fcf60, 0x2, 0x2}, 0x0, 0xc0009c6bd0})
...
```
All of the others fails with the exact same error; representative example: 
```
$ earthly -v
earthly version v0.6.15 05fc449487ad0c8a1721b4fbfc527eb9870dfcfd linux/amd64; Ubuntu 20.04

$ earthly --no-cache +broken 
<snip>
+save-optional-have-contents | --> SAVE ARTIFACT --if-exists /foo +save-optional-have-contents/foo
             +broken | --> COPY +save-optional-have-contents/* ./
             +broken | WARN: (COPY +save-optional-have-contents/* ./) /* not found
Error: build target: build main: failed to solve: /* not found
```

Reproduction(s):
```earthly
VERSION 0.6
FROM alpine
WORKDIR /test

work-fine:
    BUILD +save-optional-have-contents
    BUILD +save-optional-empty
    BUILD +save-required-have-contents
    BUILD +save-required-empty

    BUILD +save-optional-at-root-abs-path-cwd-root
    BUILD +save-optional-at-root-rel-path-cwd-root
    BUILD +save-optional-buried-abs-path-cwd-root
    BUILD +save-optional-buried-self-path-cwd-buried
    BUILD +save-optional-buried-rel-path-cwd-buried
    BUILD +save-optional-buried-abs-path-cwd-buried

    COPY +save-optional-at-root-rel-path-cwd-root/* ./
    COPY +save-optional-buried-rel-path-cwd-buried/* ./

    BUILD +save-optional-panic-ok-if-required

    COPY +save-required-have-contents/* ./
    COPY +save-required-empty/* ./
    SAVE ARTIFACT ./

broken:
    BUILD +save-optional-panic

    COPY +save-optional-buried-abs-path-cwd-buried/* ./
    COPY +save-optional-buried-self-path-cwd-buried/* ./
    COPY +save-optional-buried-abs-path-cwd-root/* ./
    COPY +save-optional-at-root-abs-path-cwd-root/* ./

    COPY +save-optional-have-contents/* ./
    COPY +save-optional-empty/* ./

save-optional-have-contents:
    RUN mkdir /foo && touch /foo/bar
    SAVE ARTIFACT --if-exists /foo

save-optional-empty:
    RUN mkdir /foo
    SAVE ARTIFACT --if-exists /foo

save-required-have-contents:
    RUN mkdir /foo && touch /foo/bar
    SAVE ARTIFACT /foo

save-required-empty:
    RUN mkdir /foo
    SAVE ARTIFACT /foo

save-optional-at-root-abs-path-cwd-root:
    WORKDIR /
    RUN mkdir /foo && touch /foo/bar
    SAVE ARTIFACT --if-exists /foo

save-optional-at-root-rel-path-cwd-root:
    WORKDIR /
    RUN mkdir /foo && touch bar
    SAVE ARTIFACT --if-exists foo

save-optional-buried-abs-path-cwd-root:
    WORKDIR /
    RUN mkdir -p /foo/bar && touch /foo/bar/baz
    SAVE ARTIFACT --if-exists /foo/bar

save-optional-buried-self-path-cwd-buried:
    WORKDIR /foo/bar
    RUN touch baz
    SAVE ARTIFACT --if-exists .

save-optional-buried-rel-path-cwd-buried:
    WORKDIR /foo
    RUN mkdir bar && touch bar/baz
    SAVE ARTIFACT --if-exists bar

save-optional-buried-abs-path-cwd-buried:
    WORKDIR /foo/bar
    RUN touch baz
    SAVE ARTIFACT --if-exists /foo/bar

save-optional-panic:
    RUN mkdir /foo && touch /foo/bar
    WORKDIR /foo
    SAVE ARTIFACT --if-exists ./

save-optional-panic-ok-if-required:
    RUN mkdir /foo && touch /foo/bar
    WORKDIR /foo
    SAVE ARTIFACT ./
```

(I've already modified this script three times due to small bugs in my scenarios, and rewritten my analysis once in response.  There could still be some mistakes, but hopefully there's enough to go on to make the issue/fix clear to you folks.)

**Comment by Konubinix** [comment]
In the broken, we could add the simple

```
save-required-nothing:
   SAVE ARTIFACT nothing
```
It succeeds without complaining with version 0.8.15

**Comment by Konubinix** [comment]
Also, its behavior appears to depend on the use of `WORKDIR`

This does not save the file

```earthfile
 VERSION 0.8

 test:
     FROM alpine
     WORKDIR /app
     RUN echo foo > /app/something
     SAVE ARTIFACT --if-exists /app/something AS LOCAL something
```

While this does

```earthfile
 VERSION 0.8

 test:
     FROM alpine
     RUN mkdir /app
     RUN echo foo > /app/something
     SAVE ARTIFACT --if-exists /app/something AS LOCAL something
```

**Comment by Konubinix** [comment]
I just wasted about one day because of this (still present in earthly 0.8.15).

Thank you @rrjjvv  for the thorough analysis and for the IF test -e + SAVE ARTIFACT workaround suggestion.
