### ISSUE TITLE
Earthly v0.6.20 panics with `SIGSEGV` connecting to Remote Buildkit Host

### ISSUE THREAD

**Issue by jpugliesi** [earthly/earthly#2052]
Upon upgrading my earthly client and remote buildkit server to earthly `v0.6.20`, the earthly client is crashing with a `SIGSEGV` error immediately.

The issue does not exist with earthly `v0.6.19`

```
➜ earthly -V --buildkit-host tcp://earthly:8372 --push --no-output --use-inline-cache --save-inline-cache ./docker+build-images
Local registry host is specified while using remote buildkit. Local registry will not be used.

 1. Init 🚀
————————————————————————————————————————————————————————————————————————————————

           buildkitd | Connecting to tcp://earthly:8372...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x4804432]

goroutine 66 [running]:
github.com/moby/buildkit/client.(*Client).ListWorkers(0xc000595940, {0x4f22ef0, 0xc000050d80}, {0x0, 0x0, 0x0})
        github.com/moby/buildkit@v0.8.2-0.20210129065303-6b9ea0c202cf/client/workers.go:73 +0x1b2
github.com/earthly/earthly/buildkitd.checkConnection.func1()
        github.com/earthly/earthly/buildkitd/buildkitd.go:578 +0x1a5
created by github.com/earthly/earthly/buildkitd.checkConnection
        github.com/earthly/earthly/buildkitd/buildkitd.go:567 +0x2af

```

Earthly Version: v0.6.20

**Comment by hholst80** [comment]
I am seeing the same problem. I am not sure this will work down the line, but  it should not crash for sure?

```
➜  omnicoder git:(master) ✗ earthly --buildkit-host tcp://192.168.86.115:8372 build +all

 1. Init 🚀
————————————————————————————————————————————————————————————————————————————————

           buildkitd | Connecting to tcp://192.168.86.115:8372...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0xbef672]

goroutine 21 [running]:
github.com/moby/buildkit/client.(*Client).ListWorkers(0xc000296700, {0x13682f0, 0xc0000be0c0}, {0x0, 0x0, 0x0})
	/go/pkg/mod/github.com/earthly/buildkit@v0.0.1-0.20220716004228-a2a3e382a778/client/workers.go:73 +0x1b2
github.com/earthly/earthly/buildkitd.checkConnection.func1()
	/earthly/buildkitd/buildkitd.go:578 +0x1a5
created by github.com/earthly/earthly/buildkitd.checkConnection
	/earthly/buildkitd/buildkitd.go:567 +0x2af
➜  omnicoder git:(master) ✗ 
```

```
➜  bin rootlesskit ./buildkitd --rootless --addr tcp://0.0.0.0:8372
INFO[2022-07-30T15:38:38+02:00] auto snapshotter: using overlayfs            
INFO[2022-07-30T15:38:38+02:00] found worker "6tgmf817wx09lc3wdg3pc1mf1", labels=map[org.mobyproject.buildkit.worker.executor:oci org.mobyproject.buildkit.worker.hostname:pop-os org.mobyproject.buildkit.worker.network:host org.mobyproject.buildkit.worker.oci.process-mode:sandbox org.mobyproject.buildkit.worker.snapshotter:overlayfs], platforms=[linux/amd64 linux/amd64/v2 linux/amd64/v3 linux/386] 
WARN[2022-07-30T15:38:38+02:00] skipping containerd worker, as "/run/containerd/containerd.sock" does not exist 
INFO[2022-07-30T15:38:38+02:00] found 1 workers, default="6tgmf817wx09lc3wdg3pc1mf1" 
WARN[2022-07-30T15:38:38+02:00] currently, only the default worker can be used. 
WARN[2022-07-30T15:38:38+02:00] TLS is not enabled for tcp://0.0.0.0:8372. enabling mutual TLS authentication is highly recommended 
INFO[2022-07-30T15:38:38+02:00] running server on [::]:8372           
```

**Comment by alexcb** [comment]
@jpugliesi (and @hholst80) are you sure your remote buildkit instance is **also** running `v0.6.20`?

I can only replicate this issue when using earthly `v0.6.20` against the `earthly/buildkit` `v0.6.19` image.

(we have an unreleased fix for this, which will also make it easier to deal with version-mix-match-related-backwards-compatibility issues in the future)

**Comment by hholst80** [comment]
I tried with both a standalone buildkitd (most recent version released) and the earthly image with the same result.

**Comment by alexcb** [comment]
> standalone buildkitd

this definitely won't work -- earthly requires the `earthly/buildkit` image, and doesn't work with the upstream moby/buildkit version.

in my test, I copied and pasted

```
docker run --privileged -t -v earthly-tmp:/tmp/earthly:rw -e BUILDKIT_TCP_TRANSPORT_ENABLED=true -p 8372:8372 earthly/buildkitd:v0.6.20
```

from https://hub.docker.com/r/earthly/buildkitd

and used the same `v0.6.20` release against this instance which was running on a second computer on my network.

Can you elaborate on how you are running `earthly/buildkitd:v0.6.20`?

**Comment by hholst80** [comment]
6.19 works but 6.20 fails with the following backend:

```
❯ docker inspect buildkitd
[
    {
        "Id": "0ad36708f94ec1afca61121feaaafc3eafe985a290f447cc94dafa535ce9b0ae",
        "Created": "2022-08-03T17:20:13.266609396Z",
        "Path": "/usr/bin/entrypoint.sh",
        "Args": [
            "buildkitd",
            "--config=/etc/buildkitd.toml"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 526459,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2022-08-03T17:20:13.6132104Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:43089e2d84441f43816144c4e476dab310c1e07448a4d7b0379a91571ceb5b85",
        "ResolvConfPath": "/home/om/.local/share/docker/containers/0ad36708f94ec1afca61121feaaafc3eafe985a290f447cc94dafa535ce9b0ae/resolv.conf",
        "HostnamePath": "/home/om/.local/share/docker/containers/0ad36708f94ec1afca61121feaaafc3eafe985a290f447cc94dafa535ce9b0ae/hostname",
        "HostsPath": "/home/om/.local/share/docker/containers/0ad36708f94ec1afca61121feaaafc3eafe985a290f447cc94dafa535ce9b0ae/hosts",
        "LogPath": "/home/om/.local/share/docker/containers/0ad36708f94ec1afca61121feaaafc3eafe985a290f447cc94dafa535ce9b0ae/0ad36708f94ec1afca61121feaaafc3eafe985a290f447cc94dafa535ce9b0ae-json.log",
        "Name": "/buildkitd",
        "RestartCount": 0,
        "Driver": "fuse-overlayfs",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": null,
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {
                "8372/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "8372"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "CgroupnsMode": "private",
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 200,
            "PidMode": "",
            "Privileged": true,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": [
                "label=disable"
            ],
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "KernelMemory": 0,
            "KernelMemoryTCP": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": null,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": null,
            "ReadonlyPaths": null
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/home/om/.local/share/docker/fuse-overlayfs/99ab9c3aa6532eec3db30f466c6cc826187decc6fc0dcb054702e19313b06d5f-init/diff:/home/om/.local/share/docker/fuse-overlayfs/0a8c6a77c153c4805141d19b378422b65110a9b06185d5cfb244ac22db60591b/diff:/home/om/.local/share/docker/fuse-overlayfs/aede41a365d90bd992471035fc66b6d0173ac5ecc88297c919322d5c410b7203/diff:/home/om/.local/share/docker/fuse-overlayfs/a30dc64126f49b290702fe6d7fc4b2185e2d8fe41a6a893926f1b48d89bc2426/diff:/home/om/.local/share/docker/fuse-overlayfs/365db0647687e5e88a42c88d8844f64d21cb298c270901afdd5bb9f9bd63b1ff/diff:/home/om/.local/share/docker/fuse-overlayfs/b9301581ee1978b8cd85bec62b273482b4cf8be97a7970d530e758f404ff74e9/diff:/home/om/.local/share/docker/fuse-overlayfs/37fed1c8b3ec093d86daf32e32c7e8093bc034bfa07cb859856c5decdaa9b3c1/diff:/home/om/.local/share/docker/fuse-overlayfs/ddaf20687dc33ab5337b97f4366ee8bda927bfe981555338917988574ec8ea62/diff:/home/om/.local/share/docker/fuse-overlayfs/789f42d9782f640451ba4f1e389196b4951990f083bc637cc8e38c3ed95386be/diff:/home/om/.local/share/docker/fuse-overlayfs/0acda6ca21c7498266df29c1bcebb0e01725983779033577037da16de4730b5a/diff:/home/om/.local/share/docker/fuse-overlayfs/c33017db99038797c9cae8b79c1e878a9ca600eb7a0ae6be79feae863763cb67/diff:/home/om/.local/share/docker/fuse-overlayfs/ad2ee5f13219f50a60f79289589e289313bcc38ba99acd5d88481f2854611311/diff:/home/om/.local/share/docker/fuse-overlayfs/776a71be4916bd4c26f48a20a4216a52748743b2df63f23e6aafe376d2bb236d/diff:/home/om/.local/share/docker/fuse-overlayfs/66bb6e30ae016afd58ad316b662a408f354cbc1a7832ebb1f8a357693bdd160d/diff:/home/om/.local/share/docker/fuse-overlayfs/bede639ddb33df2ca4822c8695946c3c7dfcb3aeeca8ef98bb42b3e23ee2720c/diff:/home/om/.local/share/docker/fuse-overlayfs/292509d88b7db646dfcc662f1210e658f1e8dc73b0623a07bde5f38e7cfb13d7/diff:/home/om/.local/share/docker/fuse-overlayfs/6168d6c6bb9bca23fa2618c7dc7d79d58d17ac51bcf0316efc6d560631c8bccb/diff:/home/om/.local/share/docker/fuse-overlayfs/9116738f4f88bea96bdab3bc3b3887a695eec9bc145a27f46098e27ac98ea9fb/diff:/home/om/.local/share/docker/fuse-overlayfs/40055ed55ec7e1a9bf53c8a254f355faab73b0c39f169c851c0e22ec18b55979/diff:/home/om/.local/share/docker/fuse-overlayfs/b2cb5379f8b311f91c9b283f898d8b3ffedb8118985a097d354f220bb8259bc6/diff",
                "MergedDir": "/home/om/.local/share/docker/fuse-overlayfs/99ab9c3aa6532eec3db30f466c6cc826187decc6fc0dcb054702e19313b06d5f/merged",
                "UpperDir": "/home/om/.local/share/docker/fuse-overlayfs/99ab9c3aa6532eec3db30f466c6cc826187decc6fc0dcb054702e19313b06d5f/diff",
                "WorkDir": "/home/om/.local/share/docker/fuse-overlayfs/99ab9c3aa6532eec3db30f466c6cc826187decc6fc0dcb054702e19313b06d5f/work"
            },
            "Name": "fuse-overlayfs"
        },
        "Mounts": [
            {
                "Type": "volume",
                "Name": "27db8b18c8fb864f7fd4481db863c23e36738e91ff8e0d4b021f6bbd74635793",
                "Source": "/home/om/.local/share/docker/volumes/27db8b18c8fb864f7fd4481db863c23e36738e91ff8e0d4b021f6bbd74635793/_data",
                "Destination": "/tmp/earthly",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "volume",
                "Name": "de39befd82425bb06b4c42be7ae3bf4740563f2acc19cfb4fc390c3af0601085",
                "Source": "/home/om/.local/share/docker/volumes/de39befd82425bb06b4c42be7ae3bf4740563f2acc19cfb4fc390c3af0601085/_data",
                "Destination": "/var/lib/buildkit",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],
        "Config": {
            "Hostname": "0ad36708f94e",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": true,
            "AttachStderr": true,
            "ExposedPorts": {
                "8372/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "BUILDKIT_TCP_TRANSPORT_ENABLED=true",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "EARTHLY_RESET_TMP_DIR=false",
                "EARTHLY_TMP_DIR=/tmp/earthly",
                "BUILDKIT_DEBUG=false",
                "BUILDKIT_MAX_PARALLELISM=20",
                "BUILDKIT_LOCAL_REGISTRY_LISTEN_PORT=8371",
                "CACHE_SIZE_MB=0",
                "CACHE_SIZE_PCT=0",
                "NETWORK_MODE=cni",
                "EARTHLY_GIT_HASH=ad869c06c884b10f88948b5852ab22b4d7262e20",
                "BUILDKIT_BASE_IMAGE=github.com/earthly/buildkit:a2a3e382a7782588b741932d7ee9484358bac157+build",
                "EARTHLY_CACHE_VERSION=2"
            ],
            "Cmd": null,
            "Image": "earthly/buildkitd:v0.6.20",
            "Volumes": {
                "/tmp/earthly": {},
                "/var/lib/buildkit": {}
            },
            "WorkingDir": "",
            "Entrypoint": [
                "/usr/bin/entrypoint.sh",
                "buildkitd",
                "--config=/etc/buildkitd.toml"
            ],
            "OnBuild": null,
            "Labels": {}
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "35bd76922138f09d316016145c62bf9e6f9c8bfbb9c719805053566e7a6dc802",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "8372/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "8372"
                    },
                    {
                        "HostIp": "::",
                        "HostPort": "8372"
                    }
                ]
            },
            "SandboxKey": "/run/user/1000/docker/netns/35bd76922138",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "2aa84a497af7f3b7bb90da8a4c91810bad2e50fe2aff41c9f9104990b16b366d",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "172.17.0.2",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "02:42:ac:11:00:02",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "f62483fda08988529ace4427716f6423adc33bdcd657268cb1c941254390265c",
                    "EndpointID": "2aa84a497af7f3b7bb90da8a4c91810bad2e50fe2aff41c9f9104990b16b366d",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:11:00:02",
                    "DriverOpts": null
                }
            }
        }
    }
]
```

**Comment by vladaionescu** [comment]
This has been fixed in the latest release. A 0.6.21 Earthly will work with a 0.6.19 Earthly-flavored Buildkit.
