### ISSUE TITLE
Earthly v0.6.30 panics with SIGSEGV connecting to Remote Docker Host (Probably M1 Chip issue)

### ISSUE THREAD

**Issue by genestack-okunitsyn** [earthly/earthly#2527]
```bash
└──╼ $ earthly -P +build
 1. Init 🚀
————————————————————————————————————————————————————————————————————————————————

           buildkitd | Found buildkit daemon as docker container (earthly-buildkitd)

 2. Build 🔧
————————————————————————————————————————————————————————————————————————————————

d/genestack-builder:latest | --> Load metadata linux/amd64
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x10 pc=0x1032269e4]

goroutine 152 [running]:
github.com/moby/buildkit/session/auth.(*CredentialsResponse).MarshalToSizedBuffer(0x0, {0x103ff0230, 0x0, 0x1036d67a0?})
	github.com/moby/buildkit@v0.8.2-0.20210129065303-6b9ea0c202cf/session/auth/auth.pb.go:1066 +0x24
github.com/moby/buildkit/session/auth.(*CredentialsResponse).Marshal(0x0)
	github.com/moby/buildkit@v0.8.2-0.20210129065303-6b9ea0c202cf/session/auth/auth.pb.go:1053 +0xe4
google.golang.org/protobuf/internal/impl.legacyMarshal({{}, {0x10375af18, 0x14000886240}, {0x0, 0x0, 0x0}, 0x0})
	google.golang.org/protobuf@v1.28.1/internal/impl/legacy_message.go:402 +0x84
google.golang.org/protobuf/proto.MarshalOptions.marshal({{}, 0x98?, 0x0, 0x0}, {0x0, 0x0, 0x0}, {0x10375af18, 0x14000886240})
	google.golang.org/protobuf@v1.28.1/proto/encode.go:166 +0x1b8
google.golang.org/protobuf/proto.MarshalOptions.MarshalAppend({{}, 0xa0?, 0x67?, 0x6d?}, {0x0, 0x0, 0x0}, {0x1037458e0?, 0x14000886240?})
	google.golang.org/protobuf@v1.28.1/proto/encode.go:125 +0x70
github.com/golang/protobuf/proto.marshalAppend({0x0, 0x0, 0x0}, {0x12bcd1040?, 0x0?}, 0x0?)
	github.com/golang/protobuf@v1.5.2/proto/wire.go:40 +0x78
github.com/golang/protobuf/proto.Marshal(...)
	github.com/golang/protobuf@v1.5.2/proto/wire.go:23
google.golang.org/grpc/encoding/proto.codec.Marshal({}, {0x1036d67a0, 0x0})
	google.golang.org/grpc@v1.47.0/encoding/proto/proto.go:45 +0x54
google.golang.org/grpc.encode({0x12bba7e68?, 0x103ff0230?}, {0x1036d67a0?, 0x0?})
	google.golang.org/grpc@v1.47.0/rpc_util.go:594 +0x40
google.golang.org/grpc.(*Server).sendResponse(0x1400035efc0, {0x103757380, 0x140005e5200}, 0x14000890000, {0x1036d67a0?, 0x0}, {0x0, 0x0}, 0x0?, {0x0, ...})
	google.golang.org/grpc@v1.47.0/server.go:1063 +0x16c
google.golang.org/grpc.(*Server).processUnaryRPC(0x1400035efc0, {0x103757380, 0x140005e5200}, 0x14000890000, 0x14000296600, 0x103fa4d00, 0x0)
	google.golang.org/grpc@v1.47.0/server.go:1319 +0xbd4
google.golang.org/grpc.(*Server).handleStream(0x1400035efc0, {0x103757380, 0x140005e5200}, 0x14000890000, 0x0)
	google.golang.org/grpc@v1.47.0/server.go:1620 +0x82c
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.47.0/server.go:922 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.47.0/server.go:920 +0x290

└──╼ $ echo $DOCKER_HOST
tcp://some-ip-address:2375

└──╼ $ docker ps -a
CONTAINER ID   IMAGE                       COMMAND                  CREATED          STATUS          PORTS                      NAMES
3815b619ed05   earthly/buildkitd:v0.6.30   "/usr/bin/entrypoint…"   37 minutes ago   Up 37 minutes   127.0.0.1:8371->8371/tcp   earthly-buildkitd
```

It happened after updating macOS to the 13.1 version(M1 Pro Chip). 
Reinstalling docker/docker-compose/earthly via brew wasn't helpful.

**Comment by genestack-okunitsyn** [comment]
Oh sorry, it was a conflict between Docker Desktop and brew docker installation.

Full cleanup docker leftovers from ~/Library, /var/lib/docker/, and reinstall from homebrew was helpful.
