### ISSUE TITLE
Buildkit start failed in Gitlab CI/CD

### ISSUE THREAD

**Issue by sdaschner** [earthly/earthly#2787]
We've set up Earthly in Gitlab CI/CD in two projects, and a weird problem arose for which the Earthly build, more specifically the buildkit startup, failed.

It's interesting to note that for the "first" project it worked, for the second it failed, with the same CI/CD configuration:

**Reproducer:**

```yaml
---
image:
  name: earthly/earthly:v0.7.1

services:
  - docker:dind

variables:
  FORCE_COLOR: 1
  EARTHLY_EXEC_CMD: "/bin/sh"
  EARTHLY_DEBUG: "true"
  BUILDKIT_DEBUG: "true"

before_script:
  - |
    set -e
    earthly --verbose bootstrap
    docker login [...]

earthly:
  stage: build
  script:
  - earthly --ci --push +build
```

The `Earthfile` just included a hello world, but we didn't even get that far:

```
time="2023-03-14T13:15:27Z" level=info msg="auto snapshotter: using overlayfs"
time="2023-03-14T13:15:27Z" level=debug msg="could not read \"/tmp/earthly/buildkit/net/cni\" for cleanup: open /tmp/earthly/buildkit/net/cni: no such file or directory"
time="2023-03-14T13:15:27Z" level=debug msg="creating new network namespace i3i5sr5ctnz03ok7kqivgqtqn"
time="2023-03-14T13:15:27Z" level=debug msg="finished creating network namespace i3i5sr5ctnz03ok7kqivgqtqn"
time="2023-03-14T13:15:27Z" level=debug msg="finished setting up network namespace i3i5sr5ctnz03ok7kqivgqtqn"
time="2023-03-14T13:15:27Z" level=info msg="found worker \"gc7u44zoqsc3eghp0wfd1mh2u\", labels=map[org.mobyproject.buildkit.worker.executor:oci org.mobyproject.buildkit.worker.hostname:runner-gbyzpayv-project-12584955-concurrent-0 org.mobyproject.buildkit.worker.network:cni org.mobyproject.buildkit.worker.oci.process-mode:sandbox org.mobyproject.buildkit.worker.selinux.enabled:false org.mobyproject.buildkit.worker.snapshotter:overlayfs], platforms=[linux/amd64 linux/amd64/v2 linux/amd64/v3 linux/386]"
time="2023-03-14T13:15:27Z" level=warning msg="skipping containerd worker, as \"/run/containerd/containerd.sock\" does not exist"
time="2023-03-14T13:15:27Z" level=info msg="found 1 workers, default=\"gc7u44zoqsc3eghp0wfd1mh2u\""
time="2023-03-14T13:15:27Z" level=warning msg="currently, only the default worker can be used."
time="2023-03-14T13:15:27Z" level=info msg="Starting local registry for outputs on port 8371"
time="2023-03-14T13:15:27Z" level=warning msg="No HTTP secret provided - generated random secret. This may cause problems with uploads if multiple registries are behind a load-balancer. To provide a shared secret, fill in http.secret in the configuration file or set the REGISTRY_HTTP_SECRET environment variable." go.version=go1.19.6
time="2023-03-14T13:15:27Z" level=info msg="redis not configured" go.version=go1.19.6
time="2023-03-14T13:15:27Z" level=info msg="Starting upload purge in 3m0s" go.version=go1.19.6
time="2023-03-14T13:15:27Z" level=debug msg="cleaning up cni pool"
time="2023-03-14T13:15:27Z" level=debug msg="releasing cni network namespace i3i5sr5ctnz03ok7kqivgqtqn"
panic: unable to configure authorization (file): no access controller registered with name: file
goroutine 1 [running]:
github.com/docker/distribution/registry/handlers.NewApp({0x1c8ac98?, 0xc00061a980?}, 0xc000380a80)
	/src/vendor/github.com/docker/distribution/registry/handlers/app.go:314 +0x1cba
github.com/moby/buildkit/exporter/earthlyoutputs/registry.Serve({0x1c8ac98, 0xc00061a980}, {0xc0001ac820, 0xc})
	/src/exporter/earthlyoutputs/registry/registry.go:32 +0x10d
main.main.func3(0xc0002deb00?)
	/src/cmd/buildkitd/main.go:287 +0xc47
github.com/urfave/cli.HandleAction({0x16e1800?, 0x1a6ed48?}, 0xc000031880?)
	/src/vendor/github.com/urfave/cli/app.go:526 +0x50
github.com/urfave/cli.(*App).Run(0xc000031880, {0xc0001aa000, 0x2, 0x2})
	/src/vendor/github.com/urfave/cli/app.go:288 +0x83c
main.main()
	/src/cmd/buildkitd/main.go:351 +0xf0c
           bootstrap | Warning: Bootstrapping buildkit failed: connect provided buildkit: timeout 1m0s: could not connect to buildkit: timeout: buildkitd did not respond (in time)
           bootstrap | Bootstrapping successful.

[...]

frontend | Running command: docker info
            frontend | Running command: docker info --format={{.SecurityOptions}}
            frontend | Local registry host is specified while using remote buildkit. Local registry will not be used.
            frontend | Running command: docker info --format={{.DockerRootDir}}
            frontend | docker-shell frontend initialized.
           buildkitd | Connecting to tcp://runner-gbyzpayv-project-12584955-concurrent-0:8372...
Share your logs with an Earthly account (experimental)! Register for one at https://ci.earthly.dev/.
Error stack trace:
github.com/earthly/earthly/buildkitd.init
	/earthly/buildkitd/buildkitd.go:37
runtime.doInit
	/usr/local/go/src/runtime/proc.go:6329
runtime.doInit
	/usr/local/go/src/runtime/proc.go:6306
runtime.main
	/usr/local/go/src/runtime/proc.go:233
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1594
Error: build new buildkitd client: connect provided buildkit: timeout 1m0s: could not connect to buildkit: timeout: buildkitd did not respond (in time)
```

This problem occurred only in one of the projects. Here, the buildkit can't start because of that error in the registry code.

Any ideas how to further debug this (besides these two debug vars)?

**Comment by alexcb** [comment]
Do you have access to the full `docker logs earthly-buildkitd` output? It would be interesting to see if it handles cgroups v2 correctly, and the various CNI configs it tries to use.

**Comment by sdaschner** [comment]
It seems that the buildkit is started by the `earthly-entrypoint.sh` script of `earthly/earthly`. The output I posted is from `/var/log/buildkitd.log`.

The cgroups / CNI config the script generates is the same in both projects (the one that works and the one that doesn't):

```
# cat /etc/buildkitd.toml
debug = true
root = "/tmp/earthly/buildkit"
insecure-entitlements = [ "security.insecure" ]
[grpc]
  address = [ "tcp://0.0.0.0:8372" ]
[worker.foo]
  enabled = true
  snapshotter = "auto"
  max-parallelism = 20
  gc = true
  networkMode = "cni"
  cniBinaryPath = "/usr/libexec/cni"
  cniConfigPath = "/etc/cni/cni-conf.json"
```

```
# cat /etc/cni/cni-conf.json
{
	"cniVersion": "0.3.0",
	"name": "buildkitbuild",
	"type": "bridge",
	"bridge": "cni0",
	"isGateway": true,
	"ipMasq": true,
	"mtu": 1500,
	"ipam": {
		"type": "host-local",
		"subnet": "172.30.0.0/16",
		"routes": [
			{ "dst": "0.0.0.0/0" }
		]
	}
}
```

In general, it seems that it is executed what you see here:

```
docker run --rm --entrypoint='' earthly/earthly:v0.7.1 /bin/cat /usr/bin/earthly-entrypoint.sh 
```

**Comment by alexcb** [comment]
does the `earthly-buildkitd` container stay up? can you share the entire logs from it?

**Comment by ByungJun25** [comment]
Hello, I have a same problem. (with earthly version 0.7.4)

In my case. after first job, the docker container(dind) which ran buildkit container inside was deleted, and next job creates new docker container(dind) which create new buildkit container. But the new buildkit is failed with the logs like below.

```
starting earthly-buildkit with EARTHLY_GIT_HASH=a1c46ca2b75f21a4948fd53b5464de5a2bd90372 BUILDKIT_BASE_IMAGE=github.com/earthly/buildkit:1701faffba4d04deeba2e57f16d89afb7cc349c5+build
detected cgroups v2; buildkit/entrypoint.sh running under pid=1
Resetting dir /tmp/earthly
Autodetecting iptables
Detected iptables-nft module
sh: out of range
BUILDKIT_ROOT_DIR=/tmp/earthly/buildkit
CACHE_SIZE_MB=0
BUILDKIT_MAX_PARALLELISM=8
BUILDKIT_LOCAL_REGISTRY_LISTEN_PORT=8371
EARTHLY_ADDITIONAL_BUILDKIT_CONFIG=
CNI_MTU=1500
OOM_SCORE_ADJ=0

======== CNI config ==========
{
        "cniVersion": "0.3.0",
        "name": "buildkitbuild",
        "type": "bridge",
        "bridge": "cni0",
        "isGateway": true,
        "ipMasq": true,
        "mtu": 1500,
        "ipam": {
                "type": "host-local",
                "subnet": "172.30.0.0/16",
                "routes": [
                        { "dst": "0.0.0.0/0" }
                ]
        }
}
======== End CNI config ==========

Detected container architecture is x86_64
time="2023-05-23T14:32:02Z" level=info msg="auto snapshotter: using overlayfs"
buildkitd: plugin type="bridge" name="buildkitbuild" failed (add): running [/sbin/iptables -t nat -A CNI-d3de856303d475f9d357185ba -d 172.30.0.2/16 -j ACCEPT -m comment --comment name: "buildkitbuild" id: "8ea2xxdagg9qaa135jn5kfcd3" --wait]: exit status 4: Warning: Extension comment revision 0 not supported, missing kernel module?
iptables v1.8.8 (nf_tables):  RULE_APPEND failed (No such file or directory): rule in chain CNI-d3de856303d475f9d357185ba

CNI setup error
github.com/moby/buildkit/util/network/cniprovider.(*cniProvider).newNS
        /src/util/network/cniprovider/cni.go:247
github.com/moby/buildkit/util/network/cniprovider.(*cniPool).getNew
        /src/util/network/cniprovider/cni.go:157
github.com/moby/buildkit/util/network/cniprovider.(*cniPool).get
        /src/util/network/cniprovider/cni.go:153
github.com/moby/buildkit/util/network/cniprovider.(*cniProvider).New
        /src/util/network/cniprovider/cni.go:217
github.com/moby/buildkit/util/network/cniprovider.(*cniProvider).initNetwork
        /src/util/network/cniprovider/cni.go:85
github.com/moby/buildkit/util/network/cniprovider.New
        /src/util/network/cniprovider/cni.go:64
github.com/moby/buildkit/util/network/netproviders.Providers
        /src/util/network/netproviders/network.go:23
github.com/moby/buildkit/worker/runc.NewWorkerOpt
        /src/worker/runc/runc.go:46
main.ociWorkerInitializer
        /src/cmd/buildkitd/main_oci_worker.go:322
main.newWorkerController
        /src/cmd/buildkitd/main.go:762
main.newController
        /src/cmd/buildkitd/main.go:694
main.main.func3
        /src/cmd/buildkitd/main.go:279
github.com/urfave/cli.HandleAction
        /src/vendor/github.com/urfave/cli/app.go:524
github.com/urfave/cli.(*App).Run
        /src/vendor/github.com/urfave/cli/app.go:286
main.main
        /src/cmd/buildkitd/main.go:357
runtime.main
        /usr/local/go/src/runtime/proc.go:250
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1598
```

**Comment by danielschlegel** [comment]
Did you try to avoid using earthly image? I also had issues with this but found a workaround even without needing to use the dind service. The runner is a docker runner with mounted docker sock and privelegded access. Since this is completely internal for us we can do this. We also get cached builds like this. Read the earthly docks for further optimization of runners, e.g. mounting tmp dir to avoid high disk usage. 

image: docker:git

before_script:
  - wget https://github.com/earthly/earthly/releases/download/v0.7.4/earthly-linux-amd64 -O /usr/local/bin/earthly
  - chmod +x /usr/local/bin/earthly
  - export FORCE_COLOR=1
  - /usr/local/bin/earthly bootstrap
  - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
  # used by earthly to access remote git targets
  - |
    cat << END >> ~/.earthly/config.yml
    git:
      git.mygit.com:
        auth: https
        user: ${CI_GIT_USER}
        password: ${CI_GIT_PASSWORD} 
    END
  - cat ~/.earthly/config.yml

stages:
  - test 

test:
  stage: test
  script:
    - earthly -P +test

**Comment by danielschlegel** [comment]
My buildkit already fails on releasing network namespace.

```
Detected container architecture is x86_64
INFO[2024-02-15T13:23:45Z] auto snapshotter: using overlayfs            
WARN[2024-02-15T13:23:45Z] failed to release network namespace "eppv54jxpi2omd7pm4777eeev" left over from previous run: plugin type="loopback" failed (delete): unknown FS magic on "/tmp/earthly/buildkit/net/cni/eppv54jxpi2omd7pm4777eeev": ef53 
buildkitd: plugin type="bridge" name="buildkitbuild" failed (add): running [/sbin/iptables -t nat -A CNI-05c169dc5182f71a39330c69 -d 172.30.0.2/16 -j ACCEPT -m comment --comment name: "buildkitbuild" id: "htyrszxovafdp5v5dxln2znzu" --wait]: exit status 4: Warning: Extension comment revision 0 not supported, missing kernel module?
iptables v1.8.9 (nf_tables):  RULE_APPEND failed (No such file or directory): rule in chain CNI-05c169dc5182f71a39330c69

CNI setup error
github.com/moby/buildkit/util/network/cniprovider.(*cniProvider).newNS
        /src/util/network/cniprovider/cni.go:248
github.com/moby/buildkit/util/network/cniprovider.(*cniPool).getNew
        /src/util/network/cniprovider/cni.go:157
github.com/moby/buildkit/util/network/cniprovider.(*cniPool).get
        /src/util/network/cniprovider/cni.go:153
github.com/moby/buildkit/util/network/cniprovider.(*cniProvider).New
        /src/util/network/cniprovider/cni.go:217
github.com/moby/buildkit/util/network/cniprovider.(*cniProvider).initNetwork
        /src/util/network/cniprovider/cni.go:85
github.com/moby/buildkit/util/network/cniprovider.New
        /src/util/network/cniprovider/cni.go:64
github.com/moby/buildkit/util/network/netproviders.Providers
        /src/util/network/netproviders/network.go:23
github.com/moby/buildkit/worker/runc.NewWorkerOpt
        /src/worker/runc/runc.go:48
main.ociWorkerInitializer
        /src/cmd/buildkitd/main_oci_worker.go:323
main.newWorkerController
        /src/cmd/buildkitd/main.go:857
main.newController
        /src/cmd/buildkitd/main.go:788
main.main.func3
        /src/cmd/buildkitd/main.go:325
github.com/urfave/cli.HandleAction
        /src/vendor/github.com/urfave/cli/app.go:524
github.com/urfave/cli.(*App).Run
        /src/vendor/github.com/urfave/cli/app.go:286
main.main
        /src/cmd/buildkitd/main.go:416
runtime.main
        /usr/local/go/src/runtime/proc.go:267
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1650
        
```
