### ISSUE TITLE
Earthly panics on SAVE ARTIFACT with dash

### ISSUE THREAD

**Issue by brandonkal** [earthly/earthly#4238]
### What went wrong?

Given this Earthfile target
```Earthfile
downloader:
    FROM alpine:3.14
    RUN apk add --no-cache curl unzip tar gzip
    ENV VERSION=1.59.1
    ENV BINARY_URL=https://github.com/golangci/golangci-lint/releases/download/v$VERSION/golangci-lint-$VERSION-linux-amd64.tar.gz
    RUN curl -L $BINARY_URL -o /root/dl.tar.gz \
        && tar -xzf /root/dl.tar.gz -C /usr/local/bin \
        && rm /root/dl.tar.gz
    SAVE ARTIFACT /usr/local/bin/golangci-lint
```
Earthly panics with this non-obvious message
```log
panic: runtime error: index out of range [2] with length 0

goroutine 105 [running]:
github.com/earthly/earthly/logbus/solvermon.formatErrorMessage({0xc0003fcf30, 0x83}, {0xc000b983c0, 0x30}, 0x1, 0x3, 0x0?)
	/earthly/logbus/solvermon/vertexmon.go:120 +0x6b8
github.com/earthly/earthly/logbus/solvermon.(*vertexMonitor).parseError(0xc0008a0e10)
	/earthly/logbus/solvermon/vertexmon.go:154 +0xe5
github.com/earthly/earthly/logbus/solvermon.(*SolverMonitor).handleBuildkitStatus(0xc0000fdd40, {0xc00051beb8?, 0x0?}, 0xc000b30d20)
	/earthly/logbus/solvermon/solvermon.go:140 +0x756
github.com/earthly/earthly/logbus/solvermon.(*SolverMonitor).MonitorProgress(0x0?, {0x18a1e38?, 0xc000350820}, 0xc00007ade0)
	/earthly/logbus/solvermon/solvermon.go:62 +0x1cc
github.com/earthly/earthly/builder.(*solver).buildMainMulti.func2()
	/earthly/builder/solver.go:72 +0x26
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/go/pkg/mod/golang.org/x/sync@v0.6.0/errgroup/errgroup.go:78 +0x56
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 1
	/go/pkg/mod/golang.org/x/sync@v0.6.0/errgroup/errgroup.go:75 +0x96
```

### What should have happened?

No panic, allow dash inside artifact names

### What earthly version?

earthly version v0.8.14 6b41f8409d7ffef0d25072c2c04250074b6e3c72 linux/amd64; Ubuntu 22.04.4 LTS (Jammy Jellyfish)

**Comment by vladaionescu** [comment]
Based on the panic, I believe that the true issue is that the file doesn't exist, and that Earthly panics when trying to format the error in this case.

Offending line: https://github.com/earthly/earthly/blob/main/logbus/solvermon/vertexmon.go#L120

**Comment by brandonkal** [comment]
Yes, it is true the issue was the file did not exist. I had to rewrite the target as so:
``Earthfile
downloader:
    FROM alpine:3.14
    RUN apk add --no-cache curl unzip tar gzip
    ENV VERSION=1.59.1
    ENV BINARY_URL=https://github.com/golangci/golangci-lint/releases/download/v$VERSION/golangci-lint-$VERSION-linux-amd64.tar.gz
    RUN curl -L $BINARY_URL -o /root/dl.tar.gz \
        && mkdir /output \
        && tar -xzf /root/dl.tar.gz -C /output \
        && mv /output/golangci-lint-$VERSION-linux-amd64 /output/golangci-lint \
        && chmod +x /output/golangci-lint \
        && rm /root/dl.tar.gz
    SAVE ARTIFACT /output
```

**Comment by drgrigorov** [comment]
Hello, I have experienced the same issue - earthly panicking when trying to report missing file for SAVE TARGET.
