### ISSUE TITLE
runtime error: index out of range [2] with length 0

### ISSUE THREAD

**Issue by gz** [earthly/earthly#4284]
### What went wrong?

getting

```
  panic: runtime error: index out of range [2] with length 0

  goroutine 251 [running]:
  github.com/earthly/earthly/logbus/solvermon.formatErrorMessage({0xc000a56a00, 0x77}, {0xc000ffe020, 0x1a}, 0x1, 0x3, 0x0?)
  	/earthly/logbus/solvermon/vertexmon.go:120 +0x6b8
  github.com/earthly/earthly/logbus/solvermon.(*vertexMonitor).parseError(0xc0009285f0)
  	/earthly/logbus/solvermon/vertexmon.go:154 +0xe5
  github.com/earthly/earthly/logbus/solvermon.(*SolverMonitor).handleBuildkitStatus(0xc0001d1d20, {0xc00168feb8?, 0x920ad8?}, 0xc001e85860)
  	/earthly/logbus/solvermon/solvermon.go:140 +0x756
  github.com/earthly/earthly/logbus/solvermon.(*SolverMonitor).MonitorProgress(0x0?, {0x18a1e38?, 0xc000924af0}, 0xc00087d2c0)
  	/earthly/logbus/solvermon/solvermon.go:62 +0x1cc
  github.com/earthly/earthly/builder.(*solver).buildMainMulti.func2()
  	/earthly/builder/solver.go:72 +0x26
  golang.org/x/sync/errgroup.(*Group).Go.func1()
  	/go/pkg/mod/golang.org/x/sync@v0.6.0/errgroup/errgroup.go:78 +0x56
  created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 1
  	/go/pkg/mod/golang.org/x/sync@v0.6.0/errgroup/errgroup.go:75 +0x96
  Error: Process completed with exit code 2.
```

during earthly execution

log is here:
https://github.com/feldera/feldera/actions/runs/10713727615/job/29706246056

### What should have happened?

earthly shouldn't crash

### What earthly version?

0.8.14

**Comment by gz** [comment]
duplicate of https://github.com/earthly/earthly/issues/4221
