### ISSUE TITLE
segfault in github.com/armon/circbuf

### ISSUE THREAD

**Issue by jazzdan** [earthly/earthly#798]
Encountered when executing a `RUN` that looked like this:

```
RUN --mount=type=cache,target=/root/.npm npm install
```

it was reproducible.

Output looked like this:

```
+backend-standalone-test | Setting up librsvg2-common:amd64 (2.48.9-1ubuntu0.20.04.1) ...
+backend-standalone-test | Setting up x11-xkb-utils (7.7+5) ...
+backend-standalone-test | Setting up xserver-common (2:1.20.9-2ubuntu1.2~20.04.1) ...
+backend-standalone-test | Setting up xvfb (2:1.20.9-2ubuntu1.2~20.04.1) ...
+backend-standalone-test | Setting up adwaita-icon-theme (3.36.1-2ubuntu0.20.04.2) ...
+backend-standalone-test | update-alternatives: using /usr/share/icons/Adwaita/cursor.theme to provide /usr/share/icons/default/index.theme (x-cursor-theme) in auto mode
+backend-standalone-test | Setting up humanity-icon-theme (0.6.15) ...
+backend-standalone-test | Setting up ubuntu-mono (19.04-0ubuntu3) ...
+backend-standalone-test | Processing triggers for systemd (245.4-4ubuntu3.4) ...
+backend-standalone-test | Processing triggers for mime-support (3.64ubuntu1) ...
+backend-standalone-test | Processing triggers for libglib2.0-0:amd64 (2.64.6-1~ubuntu20.04.1) ...
+backend-standalone-test | Setting up libgtk-3-0:amd64 (3.24.20-0ubuntu1) ...
+backend-standalone-test | Processing triggers for libc-bin (2.31-0ubuntu9.1) ...
+backend-standalone-test | Setting up libgtk-3-bin (3.24.20-0ubuntu1) ...
+backend-standalone-test | Setting up firefox (85.0.1+build1-0ubuntu0.20.04.1) ...
+backend-standalone-test | update-alternatives: using /usr/bin/firefox to provide /usr/bin/gnome-www-browser (gnome-www-browser) in auto mode
+backend-standalone-test | update-alternatives: using /usr/bin/firefox to provide /usr/bin/x-www-browser (x-www-browser) in auto mode
+backend-standalone-test | Please restart all running instances of firefox, or you will experience problems.
+backend-standalone-test | Processing triggers for libgdk-pixbuf2.0-0:amd64 (2.40.0+dfsg-3ubuntu0.2) ...
+backend-standalone-test | --> COPY package.json package-lock.json tsconfig.json .
+backend-standalone-test | --> RUN npm install
+backend-standalone-test | ERROR: Command exited with non-zero code: RUN npm install
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1a4cd10]

goroutine 31 [running]:
github.com/armon/circbuf.(*Buffer).Bytes(...)
	github.com/armon/circbuf@v0.0.0-20190214190532-5111143e8da2/circbuf.go:71
github.com/earthly/earthly/builder.(*solverMonitor).monitorProgress(0xc00089a460, 0x1e45820, 0xc0000a35c0, 0xc0000ea780, 0x1cf7a81, 0x4, 0xc0000a81f0, 0x0, 0x0, 0x0)
	github.com/earthly/earthly/builder/solver_monitor.go:321 +0xd90
github.com/earthly/earthly/builder.(*solver).buildMainMulti.func2(0xc0000ea480, 0xc0000a81f0)
	github.com/earthly/earthly/builder/solver.go:124 +0x67
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc00011baa0, 0xc0000a3680)
	golang.org/x/sync@v0.0.0-20201207232520-09787c993a3a/errgroup/errgroup.go:57 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync@v0.0.0-20201207232520-09787c993a3a/errgroup/errgroup.go:54 +0x66
```

Earthly version:

```
❯ earthly --version
earthly version v0.5.2 darwin/amd64
```

I fixed it by removing the `--mount` flag.

**Comment by vladaionescu** [comment]
Thanks for the report, Dan! Will be fixed in the next release.
