### ISSUE TITLE
panic on hello-world

### ISSUE THREAD

**Issue by farwydi** [earthly/earthly#980]
i got this error on WSL2

After:
```
sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/latest/download/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly && /usr/local/bin/earthly bootstrap'

earthly github.com/earthly/hello-world:main+hello
```

```
-> % earthly --version
earthly version v0.5.12 linux/amd64
```

```
-> % earthly github.com/earthly/hello-world:main+hello
           buildkitd | Found buildkit daemon as docker container (earthly-buildkitd)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xda5faa]

goroutine 56 [running]:
github.com/jdxcode/netrc.(*Machine).Get(...)
        /go/pkg/mod/github.com/jdxcode/netrc@v0.0.0-20210204082910-926c7f70242a/netrc.go:217
github.com/earthly/earthly/buildcontext.(*GitLookup).lookupNetRCCredential(0xc0003b80c0, 0xc000040150, 0xa, 0x1141d76, 0x5, 0x0, 0x0, 0x2, 0xc000328658)
        /earthly/buildcontext/gitlookup.go:249 +0x10a
github.com/earthly/earthly/buildcontext.(*GitLookup).makeCloneURL(0xc0003b80c0, 0xc0000a8200, 0xc000040150, 0xa, 0xc000328778, 0x17, 0x17, 0x0, 0x0, 0x0, ...)
        /earthly/buildcontext/gitlookup.go:298 +0x5e9
github.com/earthly/earthly/buildcontext.(*GitLookup).GetCloneURL(0xc0003b80c0, 0xc000040150, 0x1e, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /earthly/buildcontext/gitlookup.go:349 +0x52f
github.com/earthly/earthly/buildcontext.(*gitResolver).resolveGitProject(0xc000032340, 0x129e4a8, 0xc000095000, 0x12a1598, 0xc000274380, 0x12ae1b8, 0xc000212370, 0x7f7a91ebc500, 0x20300000000000, 0x7f7a920a5fff, ...)
        /earthly/buildcontext/git.go:131 +0xa9
github.com/earthly/earthly/buildcontext.(*gitResolver).resolveEarthProject(0xc000032340, 0x129e4a8, 0xc000095000, 0x12a1598, 0xc000274380, 0x12ae1b8, 0xc000212370, 0x23, 0x12, 0x30)
        /earthly/buildcontext/git.go:52 +0xb6
github.com/earthly/earthly/buildcontext.(*Resolver).Resolve(0xc00000e2e8, 0x129e4a8, 0xc000095000, 0x12a1598, 0xc000274380, 0x12ae1b8, 0xc000212370, 0xc0001e9ce2, 0xc0001e9ce2, 0x1f)
        /earthly/buildcontext/resolver.go:75 +0x507
github.com/earthly/earthly/earthfile2llb.Earthfile2LLB(0x129e4a8, 0xc000095000, 0xc000040150, 0x1e, 0xc00004016f, 0x4, 0x0, 0x0, 0x0, 0x0, ...)
        /earthly/earthfile2llb/earthfile2llb.go:96 +0x109
github.com/earthly/earthly/builder.(*Builder).convertAndBuild.func2(0x129e4a8, 0xc000095000, 0x12a1598, 0xc000274380, 0x0, 0xc0004b3d78, 0xb5c728)
        /earthly/builder/builder.go:165 +0x3878
github.com/moby/buildkit/frontend/gateway/grpcclient.(*grpcClient).Run(0xc000274380, 0x129e4a8, 0xc000095000, 0xc000582680, 0x0, 0x0)
        /go/pkg/mod/github.com/earthly/buildkit@v0.7.1-0.20210428195454-c1749dff2545/frontend/gateway/grpcclient/client.go:188 +0x142
github.com/moby/buildkit/client.(*Client).Build.func2(0xc00043a281, 0x19, 0xc00018a3f0, 0x0, 0x0)
        /go/pkg/mod/github.com/earthly/buildkit@v0.7.1-0.20210428195454-c1749dff2545/client/build.go:56 +0x2a2
github.com/moby/buildkit/client.(*Client).solve.func3(0x0, 0x0)
        /go/pkg/mod/github.com/earthly/buildkit@v0.7.1-0.20210428195454-c1749dff2545/client/solve.go:233 +0x6e
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc000590a20, 0xc00059aa00)
        /go/pkg/mod/golang.org/x/sync@v0.0.0-20201207232520-09787c993a3a/errgroup/errgroup.go:57 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
        /go/pkg/mod/golang.org/x/sync@v0.0.0-20201207232520-09787c993a3a/errgroup/errgroup.go:54 +0x66
```

**Comment by vladaionescu** [comment]
Thanks for the report @farwydi - can you post your `~/.netrc` file, with any sensitive information redacted out?

**Comment by alexcb** [comment]
I can replicate this if I create an invalid netrc file; e.g.

    echo "invalid netrc file" > ~/.netrc; SSH_AUTH_SOCK="" ./build/linux/amd64/earthly github.com/earthly/hello-world:main+hello

**Comment by alexcb** [comment]
https://github.com/earthly/earthly/pull/981 should fix this issue.

**Comment by farwydi** [comment]
```
-> % cat ~/.netrc
machine gitlab.com login leon.zharikov@gmail.com ********** *************


```

I don't remember why I need this file, but I just deleted it and it worked.
Thank you for such a quick response!
